### ISSUE TITLE
Break problem

### ISSUE THREAD

**Issue by luca-saggese** [VROOM-Project/vroom#364] opened 2020-07-13 12:50 UTC
I'm experiencing a problem with new 1.7 docker image, it seems that it starts routing only after the break, if for example i've a driver with working hours 8:00 18:00 with a break within 12:00 and 12:30 first delivery is just after the break, if needed i can provide my json data

**Comment by jcoupey** [comment] 2020-07-13 13:21
We offer the guarantee that all breaks provided in input will be taken in vehicle routes, but there is no guarantee that the break will necessarily be between other steps. There are indeed situations (think half day of workload or specific jobs time windows) where it makes more sense to set the break right before or after all the steps... This is still considered valid with regard to the problem description.

Yes, a json sample file [with embedded matrix](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) would be useful for more feedback.

**Comment by luca-saggese** [comment] 2020-07-13 14:54
in my car i've an unrouted shipment because of the time window being before of all breaks, will include the son of the request

thanks

**Comment by luca-saggese** [comment] 2020-07-13 17:02
here an example JSON

{"vehicles":[{
"id":1,"start":[2.109235525131226,41.358489031787585],"end":[2.109187245368958,41.35847777022954],"time_window":[28800,86340],"breaks":[{
"service":3600,"time_windows":[[43200,45000]],"id":2001}],"capacity":[5500,5500,35]},{
"id":2,"start":[2.109511,41.35858],"end":[2.109511,41.35858],"time_window":[28800,50400],"breaks":[{
"service":3600,"time_windows":[[43200,45000]],"id":2002}],"capacity":[2500,5000,35]}],"shipments":[{
"amount":[1,0,0],"priority":40,"skills":[],"pickup":{
"id":1000,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":1,"location":[2.10102,41.35251],"service":600,"time_windows":[[1,50400]]}},{
"amount":[1,0,0],"priority":40,"skills":[],"pickup":{
"id":1001,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":2,"location":[2.11037,41.36055],"service":600,"time_windows":[[1,50400]]}},{
"amount":[1,0,0],"priority":40,"skills":[],"pickup":{
"id":1002,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":3,"location":[2.10761,41.34765],"service":600,"time_windows":[[1,50400]]}},{
"amount":[0,0,0],"priority":40,"skills":[],"pickup":{
"id":1003,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":4,"location":[2.10978,41.35403],"service":600,"time_windows":[[1,50400]]}},{
"amount":[0,0,0],"priority":40,"skills":[],"pickup":{
"id":1004,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":5,"location":[2.09714,41.34131],"service":600,"time_windows":[[1,50400]]}},{
"amount":[4,0,0],"priority":40,"skills":[],"pickup":{
"id":1005,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":6,"location":[2.106,41.35077],"service":600,"time_windows":[[1,50400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1006,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":7,"location":[2.10158,41.35672],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1007,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":8,"location":[2.10351,41.35057],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1008,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":9,"location":[2.0989,41.34779],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1009,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":10,"location":[2.10818,41.35441],"service":600,"time_windows":[[1,86400]]}},{
"amount":[3,0,0],"priority":30,"skills":[],"pickup":{
"id":1010,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":11,"location":[2.09374,41.34878],"service":600,"time_windows":[[1,86400]]}},{
"amount":[3,0,0],"priority":30,"skills":[],"pickup":{
"id":1011,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":12,"location":[2.10962,41.35659],"service":600,"time_windows":[[1,86400]]}},{
"amount":[3,0,0],"priority":30,"skills":[],"pickup":{
"id":1012,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":13,"location":[2.09374,41.34878],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1013,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":14,"location":[2.1019,41.35625],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1014,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":15,"location":[2.10212,41.35746],"service":600,"time_windows":[[1,86400]]}},{
"amount":[3,0,0],"priority":30,"skills":[],"pickup":{
"id":1015,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":16,"location":[2.10151,41.3572],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1016,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":17,"location":[2.11006,41.34835],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1017,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":18,"location":[2.11044,41.34803],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1018,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":19,"location":[2.1078,41.34816],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1019,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":20,"location":[2.10743,41.34853],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1020,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":21,"location":[2.10647,41.35171],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1021,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":22,"location":[2.10647,41.35171],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1022,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":23,"location":[2.10708,41.35144],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1023,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":24,"location":[2.10647,41.35171],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1024,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":25,"location":[2.1067,41.34882],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1025,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":26,"location":[2.10885,41.35227],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1026,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":27,"location":[2.10727,41.3524],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1027,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":28,"location":[2.10897,41.35029],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1028,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":29,"location":[2.10961,41.35399],"service":600,"time_windows":[[1,86400]]}},{
"amount":[3,0,0],"priority":30,"skills":[],"pickup":{
"id":1029,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":30,"location":[2.11073,41.35468],"service":600,"time_windows":[[1,86400]]}},{
"amount":[3,0,0],"priority":30,"skills":[],"pickup":{
"id":1030,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":31,"location":[2.11121,41.35237],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1031,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":32,"location":[2.11068,41.3526],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1032,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":33,"location":[2.11208,41.3503],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1033,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":34,"location":[2.11077,41.35367],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1034,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":35,"location":[2.11245,41.35086],"service":600,"time_windows":[[1,86400]]}},{
"amount":[9,0,0],"priority":30,"skills":[],"pickup":{
"id":1035,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":36,"location":[2.11457,41.35229],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1036,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":37,"location":[2.11244,41.35603],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1037,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":38,"location":[2.11091,41.35557],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1038,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":39,"location":[2.11207,41.35528],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1039,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":40,"location":[2.1111,41.35515],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1040,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":41,"location":[2.11434,41.35777],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1041,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":42,"location":[2.11435,41.3504],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1042,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":43,"location":[2.1138,41.35026],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1043,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":44,"location":[2.11404,41.35278],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1044,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":45,"location":[2.11404,41.35278],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1045,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":46,"location":[2.11351,41.35173],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1046,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":47,"location":[2.1124813,41.3564475],"service":600,"time_windows":[[1,86400]]}},{
"amount":[6,0,0],"priority":30,"skills":[],"pickup":{
"id":1047,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":48,"location":[2.11344,41.35451],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1048,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":49,"location":[2.11327,41.35444],"service":600,"time_windows":[[1,86400]]}},{
"amount":[0,0,0],"priority":30,"skills":[],"pickup":{
"id":1049,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":50,"location":[2.11473,41.35567],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1050,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":51,"location":[2.11465,41.35536],"service":600,"time_windows":[[1,86400]]}},{
"amount":[2,0,0],"priority":30,"skills":[],"pickup":{
"id":1051,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":52,"location":[2.11438,41.35337],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1052,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":53,"location":[2.11328,41.35399],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1053,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":54,"location":[2.11398,41.35465],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":30,"skills":[],"pickup":{
"id":1054,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":55,"location":[2.11445,41.35533],"service":600,"time_windows":[[1,86400]]}},{
"amount":[3,0,0],"priority":30,"skills":[],"pickup":{
"id":1055,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":56,"location":[2.11399,41.35419],"service":600,"time_windows":[[1,86400]]}},{
"amount":[1,0,0],"priority":10,"skills":[],"pickup":{
"id":1056,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":57,"location":[2.11179,41.36026],"service":600,"time_windows":[[0,86400]]}},{
"amount":[3,0,0],"priority":10,"skills":[],"pickup":{
"id":1057,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":58,"location":[2.11146,41.36133],"service":600,"time_windows":[[0,86400]]}},{
"amount":[4,0,0],"priority":10,"skills":[],"pickup":{
"id":1058,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":59,"location":[2.11129,41.35472],"service":600,"time_windows":[[0,86400]]}},{
"amount":[1,0,0],"priority":10,"skills":[],"pickup":{
"id":1059,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":60,"location":[2.1091,41.35348],"service":600,"time_windows":[[0,86400]]}},{
"amount":[5,0,0],"priority":10,"skills":[],"pickup":{
"id":1060,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":61,"location":[2.11364,41.35542],"service":600,"time_windows":[[0,86400]]}},{
"amount":[0,0,0],"priority":10,"skills":[],"pickup":{
"id":1061,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":62,"location":[2.11179,41.36026],"service":600,"time_windows":[[0,86400]]}},{
"amount":[1,0,0],"priority":20,"skills":[],"pickup":{
"id":1062,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":63,"location":[2.10864,41.34823],"service":600,"time_windows":[[0,86400]]}},{
"amount":[5,0,0],"priority":20,"skills":[],"pickup":{
"id":1063,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":64,"location":[2.1082458,41.3517259],"service":600,"time_windows":[[0,86400]]}},{
"amount":[2,0,0],"priority":20,"skills":[],"pickup":{
"id":1064,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":65,"location":[2.11164,41.3553],"service":600,"time_windows":[[0,86400]]}},{
"amount":[3,0,0],"priority":20,"skills":[],"pickup":{
"id":1065,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":66,"location":[2.10958,41.35448],"service":600,"time_windows":[[0,86400]]}},{
"amount":[1,0,0],"priority":20,"skills":[],"pickup":{
"id":1066,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":67,"location":[2.10925,41.35272],"service":600,"time_windows":[[0,86400]]}},{
"amount":[1,0,0],"priority":20,"skills":[],"pickup":{
"id":1067,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":68,"location":[2.11343,41.35497],"service":600,"time_windows":[[0,86400]]}},{
"amount":[1,0,0],"priority":20,"skills":[],"pickup":{
"id":1068,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":69,"location":[2.11261,41.35631],"service":600,"time_windows":[[0,86400]]}},{
"amount":[1,0,0],"priority":20,"skills":[],"pickup":{
"id":1069,"service":0,"location":[2.109511,41.35858]},"delivery":{
"id":70,"location":[2.11402,41.35327],"service":600,"time_windows":[[0,86400]]}}]}

**Comment by luca-saggese** [comment] 2020-07-13 17:03
all the delivery starts after 13:00

**Comment by luca-saggese** [comment] 2020-07-14 09:26
it works if you define jobs instead of shipments, i've tried creating a dummy job and it seems to almost work, but it leaves some shipment unassigned even if they have an higher priority and vehicles are not full

**Comment by jcoupey** [comment] 2020-07-14 14:54
I can reproduce the steps ordering in the solution you provide using the demo server. It's totally valid in the sense that all arrival times match corresponding time windows in input.

The current ordering of steps in the solution is (listing both `type` and `id`):

```bash
$ jq '.routes[0].steps[] | [.type,.id] | @csv' solution.json
"\"start\","
"\"break\",2002"
"\"pickup\",1001"
"\"pickup\",1000"
"\"delivery\",1"
"\"delivery\",2"
"\"end\","

```

Could you be more precise on why you think there is a problem by describing exactly what would be your expected list of step ids?

**Comment by luca-saggese** [comment] 2020-07-14 15:01
Yes the solution is valid, but i was expecting that the delivery would start at the start of time window of each vehicle (28800) not just after the break (43200).
If instead of shipments i use jobs then job tasks are  executed as soon as possible (28800)

**Comment by jcoupey** [comment] 2020-07-14 15:08
If you want me to fully understand your problem, please answer my question precisely:

> what would be your expected list of step ids?

Bonus point if you can specify expected start time.

**Comment by luca-saggese** [comment] 2020-07-14 17:05
i would expect:
1) start
2) pickup (arrival 28800)
3) pickup (arrival 28800)
4) delivery (arrival > 28800)
5) delivery (arrival > 28800)
6) break
7) end

**Comment by luca-saggese** [comment] 2020-07-14 17:12
for example same data using jobs instead of shipment:

{
   "vehicles":[
      {
         "id":1,
         "start":[
            2.109235525131226,
            41.358489031787585
         ],
         "end":[
            2.109187245368958,
            41.35847777022954
         ],
         "time_window":[
            28800,
            86340
         ],
         "breaks":[
            {
               "service":3600,
               "time_windows":[
                  [
                     43200,
                     45000
                  ]
               ],
               "id":2001
            }
         ],
         "capacity":[
            5500,
            5500,
            35
         ]
      },
      {
         "id":2,
         "start":[
            2.109511,
            41.35858
         ],
         "end":[
            2.109511,
            41.35858
         ],
         "time_window":[
            28800,
            50400
         ],
         "breaks":[
            {
               "service":3600,
               "time_windows":[
                  [
                     43200,
                     45000
                  ]
               ],
               "id":2002
            }
         ],
         "capacity":[
            2500,
            5000,
            35
         ]
      }
   ],
   "jobs":[
      {
         "amount":[
            1,
            0,
            0
         ],
         "priority":40,
         "skills":[

         ],
          "id":1,
          "location":[
              2.10102,
              41.35251
          ],
          "service":600,
          "time_windows":[
              [
                1,
                50400
              ]
          ]
      },
      {
         "amount":[
            1,
            0,
            0
         ],
         "priority":40,
         "skills":[
         ],
          "id":2,
          "location":[
              2.11037,
              41.36055
          ],
          "service":600,
          "time_windows":[
              [
                1,
                50400
              ]
          ]
      }
   ]
}

result 

{
   "code":0,
   "summary":{
      "cost":308,
      "unassigned":0,
      "delivery":[
         2,
         0,
         0
      ],
      "amount":[
         2,
         0,
         0
      ],
      "pickup":[
         0,
         0,
         0
      ],
      "service":4800,
      "duration":308,
      "waiting_time":0,
      "distance":3140,
      "computing_times":{
         "loading":43,
         "solving":1,
         "routing":2
      }
   },
   "unassigned":[

   ],
   "routes":[
      {
         "vehicle":2,
         "cost":308,
         "delivery":[
            2,
            0,
            0
         ],
         "amount":[
            2,
            0,
            0
         ],
         "pickup":[
            0,
            0,
            0
         ],
         "service":4800,
         "duration":308,
         "waiting_time":0,
         "distance":3140,
         "steps":[
            {
               "type":"start",
               "location":[
                  2.109511,
                  41.35858
               ],
               "load":[
                  2,
                  0,
                  0
               ],
               "arrival":41692,
               "duration":0,
               "distance":0
            },
            {
               "type":"job",
               "location":[
                  2.10102,
                  41.35251
               ],
               "id":1,
               "service":600,
               "waiting_time":0,
               "job":1,
               "load":[
                  1,
                  0,
                  0
               ],
               "arrival":41804,
               "duration":112,
               "distance":1157
            },
            {
               "type":"job",
               "location":[
                  2.11037,
                  41.36055
               ],
               "id":2,
               "service":600,
               "waiting_time":0,
               "job":2,
               "load":[
                  0,
                  0,
                  0
               ],
               "arrival":42543,
               "duration":251,
               "distance":2645
            },
            {
               "type":"break",
               "id":2002,
               "service":3600,
               "waiting_time":0,
               "load":[
                  0,
                  0,
                  0
               ],
               "arrival":43200,
               "duration":308,
               "distance":3140
            },
            {
               "type":"end",
               "location":[
                  2.109511,
                  41.35858
               ],
               "load":[
                  0,
                  0,
                  0
               ],
               "arrival":46800,
               "duration":308,
               "distance":3139
            }
         ],
         "geometry":"izl{Fi_{K~@hDNh@FVTS|EgEb@]PZdBrDdBjDh@dAHR~@lCrAtEHVFTBHBDHXHVj@pBL^L\\^hALZHVnAnDJXN^lBzEP`@Qa@mB{EO_@KYoAoDIWM[_@iAM]M_@k@qBIWIYCECIGUIWsAuE_AmCISi@eAeBkDeBsDQ[KS_@\\_FdESPMHyEvCa@TGEGAQm@{AkGWeAIYu@qCq@gCGYPOnEyDNMHXxBjHNd@HXx@zC"
      }
   ]
}

**Comment by luca-saggese** [comment] 2020-07-14 17:13
start, job, job, end

**Comment by jcoupey** [comment] 2020-07-15 13:09
> i would expect:

In that situation, and starting at 28800, you'd get the following arrival times:

1. start (arrival 28800)
2. pickup (arrival 28800) [id: 1001]
3. pickup (arrival 28800) [id: [1000]
4. delivery (arrival 28912) [id:1]
5. delivery (arrival 29651) [id:2]
6. break (arrival 43200) [id:2002]

Break start is conditioned by its time window and as delivery 2 stops at 30251, this would generate a "artificial" waiting time of 12949 before being able to take the break.

Because the break is the only element that has a tight time window in input, it "attracts" the scheduled tasks around it. If you had more tasks in input than what can be done during the afternoon, then you'd start to see the break surrounded by other steps.

Also if you badly need the other tasks to happen before the break, then it should probably translate to time windows constraints on the pickups.

**Comment by jcoupey** [comment] 2020-07-15 13:24
> for example same data using jobs instead of shipment:

The difference of behaviour you see here is not related to using jobs instead of shipments but rather to the fact that the two jobs (previously delivery points) do have a non-zero service time. When it comes to deciding whether such a job is put after or before the break, we pick the latter because it results in a earlier overall end date: with `job -> break` the ealiest end date derives from the break as `43200 + 3600 = 46800` because the whole job service time can be done before the break ; with `break -> job`, then the break ends at `46800` (at the soonest) so the earliest overall end date is `46800 + 600` with the job service time.

I agree this is a bit tricky/subtle, but if you switch the `service: 0` value to any non-zero value for both your pickups in your example with shipments, then you'll get everything done before the break for the exact same reason.

**Comment by luca-saggese** [comment] 2020-07-15 13:52
Undestood, i've put service:1 and got the desired result.

the strange think is that with a lot of shipments and some of them with a time window strict to the morning i got them unrouted. I will try more with real situation to see if it still happens.

anyway thanks a lot for your work and to help me to figure out what i was missing

**Comment by jcoupey** [comment] 2020-07-15 14:01
The break can't be optional: as soon as it's included in input, it will appear in the output steps to guarantee the route takes it into account.

The options you have are:
- not submitting a break in input if you can figure out that the workload will end up with a small route
- removing the break altogether as a post-processing step if it appears at the beginning or end of the steps.

**Comment by luca-saggese** [comment] 2020-07-15 14:06
the problem i get is still that the break attracts other tasks, so the delivery starts later, the problem with the two workarounds you mention is:

1) maybe some vehicles will not do the break and other do, so i can't figure out if is needed or not
2) removing the break is an option but i would have to recompute all arrival times taking in account time_windows, so it's not trivial

Jobs still seems the better workaround

**Comment by luca-saggese** [comment] 2020-07-15 14:15
I still think break should be optional....

**Comment by jcoupey** [comment] 2020-07-15 14:29
> the break attracts other tasks
> [...]
> i would have to recompute all arrival times taking in account time_windows, so it's not trivial

It looks like you could work around this by submitting a new single-vehicle optimization request:
- using the involved vehicle **without** the initial break
- inputting only the set of shipments that were assigned to this vehicles route

**Comment by luca-saggese** [comment] 2020-07-15 14:33
this sounds good, thanks

**Comment by jcoupey** [comment] 2020-07-24 17:53
Shall we close as this looks answered?

**Comment by luca-saggese** [comment] 2020-07-24 18:29
I think should be taken in consideration for future developments having the
breaks optionals as this is really a eorkaround not a clean solution

Il giorno ven 24 lug 2020 alle 19:54 Julien Coupey <notifications@github.com>
ha scritto:

**Comment by jcoupey** [comment] 2020-07-24 19:10
Having optional breaks is not something that will happen unless we find a significantly interesting use-case where that would be required.

For now, all requests for handling breaks I've had somehow relate to a hard constraint (think social regulation), so breaks are mandatory. Can you expand a bit on the use-case you have that may be different?

**Comment by luca-saggese** [comment] 2020-07-24 20:22
I’m working on a last mile delivery system, in that situation couriers can
have a break for lunch only if necessary and should be taken in accound
during route planning. Think at defining working time starting at 8:30 and
ending at 17:30 with a break that normally in italy is contractual agreed
as one hour starting between 12:30 and 13:00.

Il giorno ven 24 lug 2020 alle 21:11 Julien Coupey <notifications@github.com>
ha scritto:

**Comment by jcoupey** [comment] 2020-07-25 13:35
Sorry, I don't get how a break can be "contractual agreed as one hour" (so mandatory according to social regulations) and at the same time taken "only if necessary"?

**Comment by luca-saggese** [comment] 2020-07-25 13:57
It depends if you reach it you start delivering in the morbirng at 8:30 then if you pass 13:00 you should have the break but if you finish earlier you can be in pause until a new delivery is requested

Inviato da iPhone

**Comment by jcoupey** [comment] 2020-07-27 07:36
>you should have the break but if you finish earlier you can be in pause

So either way it looks like the break is not optional at all, just happening at different times depending on context. You can probably model your situation with a break that has a different/wider feasibility time window.

**Comment by jcoupey** [comment] 2020-07-31 14:23
Closing as this looks answered, feel free to re-open with new input if required.

**Closed by jcoupey** 2020-07-31 14:23 UTC
Labels: question
