### ISSUE TITLE
Mac Compilation Error

### ISSUE THREAD

**Issue by cedric-holdy** [VROOM-Project/vroom#276] opened 2019-10-07 15:25 UTC
I am on mac and I use Xcode. 
However, I cannot compile the project (v1.4.0). 
Which OS and IDE do you use?

**Comment by jcoupey** [comment] 2019-10-07 15:32
Could you copy-paste here the output of the `make` command when following the [build instructions](https://github.com/VROOM-Project/vroom/wiki/Building)?

**Comment by cedric-holdy** [comment] 2019-10-07 15:40
c++ -MMD -MP -I. -std=c++14 -Wextra -Wpedantic -Wall -O3 -DNDEBUG -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/local/include -I/usr/local/anaconda3/include -I/usr/local/include/lua -I/usr/local/anaconda3/include -I/usr/local/include -I/usr/local/include/osrm -D USE_LIBOSRM=true -c main.cpp -o main.o
c++ -MMD -MP -I. -std=c++14 -Wextra -Wpedantic -Wall -O3 -DNDEBUG -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/local/include -I/usr/local/anaconda3/include -I/usr/local/include/lua -I/usr/local/anaconda3/include -I/usr/local/include -I/usr/local/include/osrm -D USE_LIBOSRM=true -c algorithms/kruskal.cpp -o algorithms/kruskal.o
In file included from algorithms/kruskal.cpp:14:
In file included from ./algorithms/kruskal.h:13:
In file included from ./structures/generic/undirected_graph.h:17:
In file included from ./structures/generic/edge.h:13:
./structures/typedefs.h:42:19: error: implicit instantiation of undefined
      template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
const std::string DEFAULT_PROFILE = "car";
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:193:32: note:
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from algorithms/kruskal.cpp:14:
In file included from ./algorithms/kruskal.h:13:
In file included from ./structures/generic/undirected_graph.h:17:
In file included from ./structures/generic/edge.h:13:
./structures/typedefs.h:49:15: error: implicit instantiation of undefined
      template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
  std::string host;
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:193:32: note:
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from algorithms/kruskal.cpp:14:
In file included from ./algorithms/kruskal.h:13:
In file included from ./structures/generic/undirected_graph.h:17:
In file included from ./structures/generic/edge.h:13:
./structures/typedefs.h:50:15: error: implicit instantiation of undefined
      template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
  std::string port;
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:193:32: note:
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
3 errors generated.
make: *** [algorithms/kruskal.o] Error 1

**Comment by cedric-holdy** [comment] 2019-10-07 15:57
Hi, I did it. Thank you.

**Comment by jcoupey** [comment] 2019-10-07 16:07
Right, there is a missing `string` include and this has actually already been fixed in #232. You have basically two options:

- checkout the `v1.5.0-rc.1` tag to build the latest release candidate that includes the fix (that's what I'd suggest)
- stick with `v1.4.0` and add the missing includes following [those changes](https://github.com/VROOM-Project/vroom/pull/232/files) in `src/structures/typedefs.h`.

Closing as duplicate of #231.

**Closed by jcoupey** 2019-10-07 16:07 UTC
Labels: compilation

**Comment by cedric-holdy** [comment] 2019-10-07 16:21
Thank you.
