### ISSUE TITLE
job having amount zero executed?

### ISSUE THREAD

**Issue by stefanocudini** [VROOM-Project/vroom#317] opened 2020-03-31 14:32 UTC
hi,
in my case study using VROOM trought _openrouteservice-py_ inside jupyter and optain this map that show amount value(random generate for each jobs) and capacity for each two vehicles that is 5
using this simple python code:
```python
job_locs = [...coordinates...]
jobs = []
for idx, cc in enumerate(job_locs):

    amount = random.randrange(0, 3)

    jobs.append(ors.optimization.Job(
        id = idx,
        location = cc,
        amount = [amount],
    ))
...
```
![vroo](https://user-images.githubusercontent.com/47107/78037673-25704b80-736c-11ea-9a6c-555cf30926a5.png)

the most logical solution of this problem is that it must bypass jobs with zero amount.. :-/

I don't understand if it's a bug or some setting is missing from vroom

**Comment by stefanocudini** [comment] 2020-03-31 14:42
testing this problem on VROOM demo obtain same strange behaviour..
```json
{
  "vehicles": [
    {
      "capacity": [5],
      "start": [
        11.13358, 
        46.04372
      ], 
      "end": [
        11.13358, 
        46.04372
      ], 
      "id": 0
    }
  ], 
  "jobs": [
    {
      "id": 1,
      "amount": [0],
      "location": [
        11.1403, 
        46.0541
      ]
    }, 
    {
      "id": 2, 
      "amount": [0],
      "location": [
        11.13785, 
        46.04673
      ]
    }, 
    {
      "id": 3, 
      "amount": [1],
      "location": [
        11.13875, 
        46.04115
      ]
    }, 
    {
      "id": 4, 
      "amount": [1],
      "location": [
        11.13704, 
        46.05472
      ]
    }
  ]
}
```

**Comment by jcoupey** [comment] 2020-03-31 15:57
> the most logical solution of this problem is that it must bypass jobs with zero amount..

Defining a job means you need to go at the given location to perform some action. The delivered amount has nothing to do with this, it just serves to impose capacity constraints based on what can fit in the vehicle.

In other words, having a job with 0 delivery/pickup is totally valid, think e.g. a situation with a service or maintenance task at that location.

If you want to avoid going at a place because delivered amount is zero on your side, you should simply rule it out and not put it in the submitted jobs.

**Comment by jcoupey** [comment] 2020-04-02 22:59
Closing as answered, feel free to reopen if required.

**Closed** 2020-04-02 22:59 UTC
Labels: question

**Comment by stefanocudini** [comment] 2020-04-03 10:30
for now I have solved with the workaround you suggested, if someone in the future wants to attend the discussion it will be interesting

many thanks

**Comment by jcoupey** [comment] 2020-04-03 10:33
Technically this is not a workaround, as visiting jobs with `0` amount/delivery/pickup **is** expected behaviour.

**Comment by stefanocudini** [comment] 2020-04-06 10:21
yes sorry i was wrong to sayng: workaround

I have been studying vroom for a short time and I did not yet have in mind all the scenarios that it foresees, for example the pickup as well as the deliveries
