### ISSUE TITLE
Error: 0 on local demo

### ISSUE THREAD

**Issue by emocanu** [VROOM-Project/vroom#209] opened 2019-02-08 07:21 UTC
Hi,
I've installed OSRM and launched it:

> [info] starting up engines, v5.22.0
> [info] Threads: 2
> [info] IP address: 0.0.0.0
> [info] IP port: 5000
> [info] http 1.1 compression handled by zlib version 1.2.11
> [info] Listening on: 0.0.0.0:5000
> [info] running and waiting for requests
> [info] 07-02-2019 17:34:07 4.52244ms 127.0.0.1 - curl/7.58.0 400 /

The curl related line is because I've tested it with curl.

The vroom-express is started, it does not displays anything but:

> vroom-express@0.1.0 start /home/osrm/vroom-express
> node src/index.js
vroom-express listening on port 3000!

The frontend is also running:

> vroom-frontend@0.3.0 serve /home/osrm/vroom-frontend
> beefy src/map.js --browserify ./node_modules/.bin/browserify --live
beefy (v2.1.8) is listening on http://127.0.0.1:9966
404    9ms        12B  /
404    1ms        12B  /
404    1ms        12B  /
200   75ms       592B  /
200    2ms       527B  /css/OpenSans.css
200   23ms    14.11KB  /node_modules/leaflet/dist/leaflet.css
200   16ms     2.62KB  /node_modules/leaflet-control-geocoder/dist/Control.Geocoder.css
200   22ms     3.23KB  /css/vroom.css
200   23ms   217.36KB  /css/fonts/OpenSans-Regular.ttf
200 1388ms   490.76KB  /src/map.js -> ./node_modules/.bin/browserify ./src/map.js
200    6ms    212.9KB  /css/fonts/OpenSans-Italic.ttf
.....

If I click on the map and try to compute a route, I get the **Error: 0** message.

The vroom is built from source and moved in /usr/local/bin

Is there anything missing in order to run the demo successfully?

**Comment by jcoupey** [comment] 2019-02-08 08:58
If you don't see the `table` and `route` requests logged by `osrm-routed`, it means the problem is that VROOM is unable to reach OSRM. This may be due to recent option changes (see https://github.com/VROOM-Project/vroom-express/issues/12), depending on the `vroom` and `vroom-express` versions you use.
- if you built `vroom` from current `master`, then you should checkout current `master` for `vroom-express` too
- if you built `vroom` at v1.3.0, then you should checkout `vroom-express` at v0.3.0

**Comment by emocanu** [comment] 2019-02-08 09:05
I built all from the master (OSRM, VROOM, vroom-express, vroom-frontend).
Yes, osrm-routed does not log `table` and `route` request.

**Comment by jcoupey** [comment] 2019-02-08 09:13
OK, so not a version problem.

Next step is to look at the POST request sent to localhost:3000 from the frontend using your browser's dev tools. Can you post the response?

You can also try narrowing down the problem by bypassing `vroom-frontend` and `vroom-express`: copy the POST data in a `input.json` file and run `vroom -i input.json` on it.

**Comment by emocanu** [comment] 2019-02-08 09:33
I used the second advice of you.
It seems to me that VROOM is working fine.

OSRM logged:
`[info] 08-02-2019 09:21:25 83.6708ms 127.0.0.1 - - 200 /table/v1/car/-2.263184,51.859532;-2.263184,51.859532;-1.994019,52.439269`

I can't attach a json file so I'll dump them here:
Input:
`{"jobs":[{"id":1,"description":"Green Drive, Birmingham","location":[-1.9940185546875002,52.43926935464697]}],
 "vehicles":[{"id":1,"start":[-2.2631835937500004,51.85953150985473],"startDescription":"Spinnaker Road, Gloucester","end":[-2.2631835937500004,51.85953150985473],"endDescription":"Spinnaker Road, Gloucester"}],
 "options":{"g":true}
}`
Output:
`{"code":0,"summary":{"cost":7528,"unassigned":0,"service":0,"duration":7528,"waiting_time":0,"computing_times":{"loading":85,"solving":0}},"unassigned":[],"routes":[{"vehicle":1,"cost":7528,"service":0,"duration":7528,"waiting_time":0,"steps":[{"type":"start","location":[-2.2631835937500006,51.85953150985473],"arrival":0,"duration":0},{"type":"job","location":[-1.9940185546875,52.43926935464697],"job":1,"service":0,"waiting_time":0,"arrival":3716,"duration":3716},{"type":"end","location":[-2.2631835937500006,51.85953150985473],"arrival":7528,"duration":7528}]}]}`

**Comment by emocanu** [comment] 2019-02-08 09:34
Sorry, wrong button.

**Comment by jcoupey** [comment] 2019-02-08 09:59
> I used the second advice of you. It seems to me that VROOM is working fine.

OK, so far so good. What does the POST request response looks like as seen from your browser running the frontend?

**Comment by emocanu** [comment] 2019-02-08 10:30
The thing is that I have only ssh access to that server.
I can use the demo from outside, but not really on that computer.
I started to log from JS in order to find the issue.
This is from vroom-frontend\src\utils\solution_handler.js, before
`xhttp.send(JSON.stringify(input));`

`{"jobs":[{"id":1,"description":"Green Drive, Birmingham","location":[-1.9940185546875002,52.43926935464697]}],"vehicles":[{"id":1,"start":[-2.2631835937500004,51.85953150985473],"startDescription":"Spinnaker Road, Gloucester","end":[-2.2631835937500004,51.85953150985473],"endDescription":"Spinnaker Road, Gloucester"}],"options":{"g":true}}`

In which file & line shall I log for POST request response, please?

**Comment by emocanu** [comment] 2019-02-08 11:33
Update: I installed Chrome and used CORS.
I've got 2 errors when to compute the route.
I attach them as log file saved from Chrome console.

[1549625220484.log](https://github.com/VROOM-Project/vroom/files/2844895/1549625220484.log)

**Comment by jcoupey** [comment] 2019-02-08 12:00
From your log:
```
map.js:17087 OPTIONS http://localhost:3000/ net::ERR_CONNECTION_REFUSED
map.js:17087 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:3000/'.
```

For some reason related to your machine configuration, the browser can't connect to localhost:3000. I don't think there is much we can do on the VROOM side here.

**Comment by emocanu** [comment] 2019-02-08 12:16
Yeah, I thought that too. However:
$ sudo netstat -ntlp | grep LISTEN
```

tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      1899/osrm-routed
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      985/mysqld
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      683/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      8264/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1154/master
tcp6       0      0 :::9966                 :::*                    LISTEN      11135/node
tcp6       0      0 :::80                   :::*                    LISTEN      962/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      8264/sshd
tcp6       0      0 :::3000                 :::*                    LISTEN      11112/node
tcp6       0      0 :::25                   :::*                    LISTEN      1154/master
```

Thank you.

**Comment by jcoupey** [comment] 2019-02-08 12:52
Well, you can always check that `vroom-express` is reachable using curl:
```
curl --header "Content-Type:application/json" --data @input.json http://localhost:3000
```

In that case, the problem only comes from the browser running the frontend.

**Comment by emocanu** [comment] 2019-02-08 13:51
Thank you. Then it must be the browser. But the map.vroom-project.org works in the same browser.

The command you suggested returns:
`
{"code":0,"summary":{"cost":7528,"unassigned":0,"service":0,"duration":7528,"waiting_time":0,"distance":164710,"computing_times":{"loading":52,"solving":0,"routing":17}},"unassigned":[],"routes":[{"vehicle":1,"cost":7528,"service":0,"duration":7528,"waiting_time":0,"distance":164710,"steps":[{"type":"start","location":[-2.2631835937500006,51.85953150985473],"arrival":0,"duration":0,"distance":0},{"type":"job","location":[-1.9940185546875,52.43926935464697],"job":1,"service":0,"waiting_time":0,"arrival":3716,"duration":3716,"distance":83456},{"type":"end","location":[-2.2631835937500006,51.85953150985473],"arrival":7528,"duration":7528,"distance":164710}],"geometry":"THIS_IS_A_REALLY_LONG_STRING"}]}`

**Comment by jcoupey** [comment] 2019-02-08 15:16
So everything works fine from the vroom-express perspective, just the browser is unable to access localhost. Closing here, feel free to re-open if you have some update.

**Closed by jcoupey** 2019-02-08 15:16 UTC
