### ISSUE TITLE
Multi-Trip

### ISSUE THREAD

**Issue by ifle** [VROOM-Project/vroom#271] opened 2019-09-30 12:20 UTC
I am trying to model the multi-trip and seems the vroom is not support it
Small example : 1 vehicle with capacity 2, start and end in the depot. 4 jobs with capacity 1.
The expected route is [depot] -> job1 -> job2 -> [depot] -> job3 -> job4 -> [depot]

```
{
    "vehicles": [{
            "id": 0,
            "start": [-122.46442293052948, 37.743751223021171],
            "end": [-122.46442293052948, 37.743751223021171],
            "capacity": [2],
            "time_window": [1569842208, 1569877199]
        }
    ],
    "jobs": [{
            "id": 1,
            "service": 0,
            "delivery": [1],
            "location": [-122.48250516051762, 37.7614746846655],
            "priority": 0
        }, {
            "id": 2,
            "service": 0,
            "delivery": [1],
            "location": [-122.46038805276355, 37.762537957357544],
            "priority": 0
        }, {
            "id": 3,
            "service": 0,
            "delivery": [1],
            "location": [-122.47817140291716, 37.731105892921242],
            "priority": 0
        }, {
            "id": 4,
            "service": 0,
            "delivery": [1],
            "location": [-122.44903061905197, 37.733351483084185],
            "priority": 0
        }
    ]
}


```

**Comment by jcoupey** [comment] 2019-09-30 12:29
Closing as duplicate of #188.

**Closed by jcoupey** 2019-09-30 12:29 UTC
