### ISSUE TITLE
Unfound route(s) from location

### ISSUE THREAD

**Issue by Stephen-Kamau** [VROOM-Project/vroom#927] opened 2023-06-02 11:27 UTC
I'm trying to use vrom and am getting this in some request  

````
{
    "code": 3,
    "error": "Unfound route(s) from location [98.329716;7.788882]"
}
````

Is there a way we can be able to ignore incase such errors occurs.  This happens when I merge more than one osm.pbf map using   
````
osmium merge country1-latest.osm.pbf country2-latest.osm.pbf  country3-latest.osm.pbf   country4-latest.osm.pbf  -o 4countries.osm.pbf --overwrite
````

**Comment by jcoupey** [comment] 2023-06-02 13:33
This error means that your routing engine was not able to evaluate the cost between some of the locations. Under the hood, we have a cost matrix with "holes" which make it impossible to do a proper optimization. So no, there is no way to ignore such errors.

What you should do is track down where the problem is: usually it means that you have locations that are snapped to different connected components at the routing level. Sounds all the more plausible if you merge several countries.

**Comment by jcoupey** [comment] 2023-06-13 12:23
Closing as answered.

**Closed by jcoupey** 2023-06-13 12:23 UTC
Labels: question
