### ISSUE TITLE
More unassigned when only vehicle start is defined, 0 unassigned with start and end both defined

### ISSUE THREAD

**Issue by cv-or** [VROOM-Project/vroom#888] opened 2023-02-21 19:56 UTC
Hi, 

I'm dealing with a routing problem with 1 vehicle and 10 shipments (using custom cost matrix). I'm running two scenarios:

1. scenario 1: both start and end of the vehicle are defined -> the result is 1 route with all shipments assigned (0 unassigned)
2. scenario 2: only start of the vehicle is defined -> the result is 1 route with 1 shipment unassigned

The result of scenario 2 is pretty unexpected. I was not expecting that removing a constraint from the problem could cause unassigned tasks, while a "more constrained" problem has 0 unassigned. What am I missing? 

I'm attaching here problems and solutions for both scenarios. 

[problems and solutions.zip](https://github.com/VROOM-Project/vroom/files/10797072/problems.and.solutions.zip)

**Comment by jcoupey** [comment] 2023-02-22 11:43
Thanks for sharing the instances. I can confirm that the second solution (obtained by forcing an end step) is better since it has 2 more assigned tasks, and also valid for the first instance of course. This means the solution we provide is suboptimal with regard to the number of assigned tasks, and we have a better one at hand.

Now the solution with all tasks included is significantly more expensive. My guess is that this is the reason why the shipment that is hard to include is always discarded by the heuristic process (without an end) when deciding what to include in the first place. Then we end up in a situation where all the rest is included and it's not possible to add that one any more. This intuition is backed by several facts:

- both solutions are quite tight in term of timing;
- both solutions are quite different;
- the solution without an end is actually a heuristic solution (no local search improvement).

So why does adding the end step result in a better solution? Well changing the end point "attracts" the route toward it, changing respective costs of including shipments, so it's no wonder the solution is different. Why it is better is just bad luck (or good depending how you see it).

When adding a constraint, the **optimal** solution can only get worse because we narrow the solution space. But since we have no optimality guarantee, we can't guarantee the solution quality will change the intuitive way.

**Comment by cv-or** [comment] 2023-02-22 13:50
Thanks a lot for the quick answer, everything makes sense. Indeed, I've slightly increased the size of the time windows of the problematic shipments (+15 minutes) and the problem is properly solved also in the scenario without the end step. 

Just a quick question: how did you find out that the given solution is a heuristic solution (and that there hasn't been any improvement during local search)? Can this information be retrieved from the solution?

**Comment by jcoupey** [comment] 2023-02-23 07:58
The solution is exactly the same when solving with `-l 0`. Setting a time-out of 0 seconds means allocating no time to the local search, so the output is the best heuristic solution.

For this instance, the local search neighborhood we have is probably pretty poor anyway:
- it has only one vehicle so all moves involving more than one route are pointless;
- it has only shipments, so the scope of intra-route modification options is reduced by the precedence constraints.

**Comment by cv-or** [comment] 2023-02-24 13:22
Thanks a lot, everything is clear. I believe we can close the issue.

**Comment by jcoupey** [comment] 2023-02-24 15:33
My point was not really about the heuristics but rather about the local search process. Setting aside a shipment-specific operator, all local search moves are quite generic and most were first designed with jobs in mind. Of course some of them easily apply to shipments but since shipments involve two tasks with extra constraints, the space of neighboring solutions is much smaller. For example:

- a relocate move taking one job from a route to another does not make sense for a shipment task since you can't simply move just a pickup or just a delivery;
- an intra-relocate move (one job put somewhere else in the same route) can make sense but with the extra restriction that moving a pickup can't happen after the matching delivery.

> if the tasks would be jobs instead of shipment

I'm afraid this is not really your choice, but depends on the use-case you have. ;-)

**Comment by jcoupey** [comment] 2023-03-24 16:42
Closing as answered.

**Closed by jcoupey** 2023-03-24 16:42 UTC
Labels: question
