### ISSUE TITLE
VROOM schedules next-day deliveries despite sufficient time windows

### ISSUE THREAD

**Issue by drutkoowski** [VROOM-Project/vroom#1099] opened 2024-04-17 13:28 UTC
Hi.

I have a perhaps typical and simple question, but I am not very familiar with vroom yet (I am using it with ORS locally).
Often when I optimize routes during the day and it is deliverable today, vroom decides to deliver it the next day.
Here is an example payload (called on 17.04.2024 ~14:00): https://pastebin.com/c2KCLtUW

As you can see, both vehicles and shipments have time windows given for delivery today. After optimization, delivery takes about 90 minutes, and the time windows have even more time available. I tried setting the priority to 100, but it still selects the next day.
Is this related to the ORS config?

Thank you for your reply in advance

**Comment by jcoupey** [comment] 2024-04-25 14:21
Thanks for sharing the payload, however it is not possible to reproduce without access to your ORS routing stack. Can you please also share [a standalone instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance)?

**Comment by drutkoowski** [comment] 2024-04-29 10:36
Thanks for feedback @jcoupey. I have run it and looks like first of all, it doesnt work for ORS - because of import error: 
![image](https://github.com/VROOM-Project/vroom/assets/101982259/22f8d3e6-7a84-4a31-a79f-dc7a320d1ce3)

After changing it to `add_matrices` it gives me another error which says: 
```
vroom-scripts\src\utils\matrix.py", line 114, in add_matrices
    for line in matrices["distances"]:
KeyError: 'distances'
```

I just commented it out and then it was able to write a result: https://pastebin.com/L9pknbVA

**Comment by jcoupey** [comment] 2024-04-29 13:28
> it doesnt work for ORS - because of import error:

Looks like this was updated for the OSRM version but not the ORS one and no one noticed so far. You're welcome to open a PR on the `vroom-script` repo with this fix!

> KeyError: 'distances'

Hum that's weird I'm pretty sure ORS used to have a `distances` key for the `matrix` endpoint. I don't seem to be able to find the full response format from either https://openrouteservice.org/dev/#/api-docs/v2/matrix/{profile}/post or https://github.com/GIScience/openrouteservice/blob/main/docs/api-reference/endpoints/matrix/index.md. Maybe we need now to add another parameter to get distances on top of travel times? Could you look at the raw response of ORS for the above request to see whether a distances matrix is included somehow?

**Comment by jcoupey** [comment] 2024-04-29 13:41
> vroom decides to deliver it the next day.

I think I understand now: you have two vehicles that model each a different day. Since the cost of using either one is exactly identical, we do not discriminate both options and return a solution for the vehicle that has "day 2" time window.

What about simply removing that vehicle from the payload? You'll then get the expected solution. More generally, it is not necessary to provide extra days/vehicles when everything can be handled with less days/vehicles in input.

**Comment by jcoupey** [comment] 2024-05-22 08:45
Closing as answered.

**Closed by jcoupey** 2024-05-22 08:45 UTC
Labels: question
