### ISSUE TITLE
A vehicle goes into a warehouse twice

### ISSUE THREAD

**Issue by vklepper** [VROOM-Project/vroom#621] opened 2021-12-03 12:35 UTC
Hi ! 
I have a vehicul that goes twice in the same warehouse to pickup some shipment.
Attached is the in and out of VROOM.
My vehicle make a first stop at the warehouse, goes to the second, passes the first one and make a second stop to finish the pickup. 

Thanx you for you advice.
We really appreciate Vroom ! 

![image](https://user-images.githubusercontent.com/16687859/144603085-199cf618-23f0-4470-bdff-6eccccb4bfbd.png)
[inAndOut.zip](https://github.com/VROOM-Project/vroom/files/7649597/inAndOut.zip)

**Comment by jcoupey** [comment] 2021-12-03 14:15
Could you please provide a response including route geometry (`-g` option) to help reproduce your visualization?

**Comment by vklepper** [comment] 2021-12-03 14:24
Of course ! 
[InAndOut.zip](https://github.com/VROOM-Project/vroom/files/7650238/InAndOut.zip)

**Comment by jcoupey** [comment] 2021-12-03 15:36
What happens here is that we're not able to discriminate between the solution that would group together pickups you labeled 2 and 4 and the solution you get because the overall cost we evaluate is identical. The route after 3 does pass in front of 2 anyway so stopping again for another pickup does not add any travel time.

You'll probably point out that both solutions are not identical overall since grouping pickups reduces total setup time. That's a limitation currently because costs are only travel-time related. When introducing setup times for v1.11, we did not account for setup time variations in the local search gain evaluation process.

**Comment by jcoupey** [comment] 2021-12-03 15:39
I think I now what's going on here but I'd like to perform another test on your instance. The thing is I don't have access to your routing stack, could you also share [a standalone version](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) with matrix included?

**Comment by vklepper** [comment] 2021-12-03 15:47
I follow the instructions and get that file with `add_osrm_matrix` command.
[input_matrix.zip](https://github.com/VROOM-Project/vroom/files/7650669/input_matrix.zip)

**Comment by jcoupey** [comment] 2021-12-03 17:04
That's what I thought: what happens here is we're not able to discriminate solution A (the one you get) and solution B that would group together pickups you labeled 2 and 4. This is because the overall cost we evaluate (i.e. travel time) is not better when grouping pickups in solution B. 

The route after 3 does pass in front of 2 anyway so stopping again for another pickup does not add any travel time. It's actually the opposite, the overall travel time surprisingly increases by 1 second for solution B (3239 over 3238 for solution A) when removing the extra stop by grouping pickups at 2 and 4. Of course this is not meaningful and is probably only a consequence of the matrix values being rounded to integers. But the fact is that from the point of view of our current optimization objective, the solution you get is better than the one that would group pickups in a natural way.

You'll probably (rightly) object that solution B is way better since grouping pickups reduces total setup time by 300 seconds while only increasing travel time by 1 second. That's something we don't take into account currently because costs are only travel-time related. When introducing setup times for v1.11, we did not account for setup time variations in the local search gain evaluation process.

**Comment by jcoupey** [comment] 2021-12-03 17:07
I'm flagging this as "suboptimal" even if it's not about actually getting a suboptimal solution per se but more about something missing in the optimization objective.

**Comment by mhosman** [comment] 2022-03-04 02:52
I have exactly the same issue but with deliveries that should be grouped (same warehouse).

**Comment by jcoupey** [comment] 2022-03-04 10:35
@mhosman can't really make guesses about your situation, but you may also be hitting #560.

**Comment by mhosman** [comment] 2022-03-07 18:19
@jcoupey my problem was due to the capacity of the vehicle. I have multiple pickup + delivery and in some cases the delivery is destined for the warehouse. Once the vehicle is reaching the capacity limit, it goes to the warehouse and after that the route continues so it's kind of a multiple-routes scenario in one. This seems to be a correct behaviour but maybe not for all scenarios. Maybe (just thinking about a solution), we could stop the route if one of the stops is equal than a defined stop location.

**Comment by ThomasRambaud** [comment] 2022-04-28 10:26
@mhosman I had the same problem. The solution is to not model the pickups. Use jobs and only model the deliveries. So you'll never go back to the warehouse mid route.

**Comment by jcoupey** [comment] 2023-12-21 11:52
Revisiting this example, the initial problem disappeared a while back. All versions after v1.13 do provide the expected setup time of 900 along with the "right" grouping of pickups. On top of that, two more shipments are assigned when comparing with the solution at the time of the original post.

Closing as fixed.

**Closed by jcoupey** 2023-12-21 11:52 UTC
Labels: too suboptimal
