### ISSUE TITLE
Feature request: max_distance for vehicle

### ISSUE THREAD

**Issue by answerquest** [VROOM-Project/vroom#973] opened 2023-08-22 15:27 UTC
Just like how we have max_travel_time parameter under vehicle, can we include a max_distance value (unit in meters I suppose) so that we can define the operating range of the vehicle?

Esp with EVs, E-rickshaws etc coming in, planning by travelled distance is coming up as more important than time in my use cases.

**Comment by jcoupey** [comment] 2023-08-22 21:36
Closing as duplicate of #354. If you're interested in making this happen soon, you're welcome to contribute funding some dev time on this feature!

**Closed by jcoupey** 2023-08-22 21:36 UTC
Labels: duplicate

**Comment by answerquest** [comment] 2023-08-23 01:49
Very sorry, was searching thru the issues first but didn't see 354
