### ISSUE TITLE
Mutliple steps pick and delivery VRP

### ISSUE THREAD

**Issue by jfulem** [VROOM-Project/vroom#925] opened 2023-05-23 13:43 UTC
Is there any example of VROOM package to solve a model, where several trucks (with a certain capacity) distribute operation machines between customers? The operation of the machine at the customer's place takes some time. Once this is done, the machine or machines are collected and moved to another customer. The key here is to keep the trucks busy, collect the machines at the customer places and minimize the travelled distance by the trucks. They all start from some central depo.

I'm looking for some example or some direction. Any help or suggestion is very appreciated. Thanks.

I started with the origin-destination matrix. But I'm not sure that's the right thing to start with

**Comment by jcoupey** [comment] 2023-05-24 11:00
Are the trucks waiting at the customers place while machines are operated?

**Comment by jfulem** [comment] 2023-05-24 11:44
They are not waiting, so I can't use the service time for it. The trucks can continue to pick up and deliver the operation machines to/from other customers. The time of the operation machine at a certain location can be precomputed.

**Comment by jcoupey** [comment] 2023-05-24 12:10
So the problem is that the availability time for "pickup after use" tasks is not known before-hand, because it depends on when the machines are dropped in the first place, which is only decided during optimization.

I don't really see how you could solve this as a single optimization problem, except if you can make strong timing assumptions.

**Comment by jfulem** [comment] 2023-05-24 12:18
All right. Thank you.

**Comment by jcoupey** [comment] 2023-06-13 12:22
Closing as answered.

**Closed by jcoupey** 2023-06-13 12:22 UTC
Labels: question
