### ISSUE TITLE
Solving a huge instance

### ISSUE THREAD

**Issue by IsaacDm** [VROOM-Project/vroom#331] opened 2020-04-22 07:55 UTC
I am exploring Standalone problem instance to solve my VRP. I am able to create a duration matrix with the help of add_osrm_matrix.py file. But I don't know how to proceed further towards generating the routes using the matrix file the code has generated.

Any help is appreciated!

**Comment by jcoupey** [comment] 2020-04-22 09:18
The optimization choices are based on the knowledge of the travel time costs for getting from/to any location in the input. This means that we need a matrix of travel times prior to starting optimization work. There are two ways to get it:

1. `vroom` fires a request to a routing engine, using the coordinates passed in input
2. users provide a custom `matrix`, and then every location passed in input has to hold a reference to its matching line/column in the matrix. This is what `location_index` is for in [this example](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#using-a-custom-matrix)

Creating [a standalone problem instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) is just a convenient way to go from option 1. to option 2. by adding the `matrix` and `location_index` keys in the original problem.

The specific script you point out relies on OSRM, so I assume you have an OSRM instance at hand. In that case, you don't need to go through the trouble of generating a standalone instance, and you should be able to run `vroom` following [the usual instructions](https://github.com/VROOM-Project/vroom/wiki/Usage). If you have any trouble, please share the commands you tried to run to provide some more background.

**Comment by IsaacDm** [comment] 2020-04-24 16:07
Thanks for responding so quickly. I am able to build the application and am able to generate output. But, I was wondering about the maximum vehicles and jobs that can be optimized?

**Comment by jcoupey** [comment] 2020-04-24 16:55
There is no limit actually, unless you feed really huge problems and are time-constrained to get a solution. You'll probably be fine if you stay in the hundreds (and even more) anyway.

What is the typical size of the problems you plan to solve?

If scaling is an issue at some point, you want to look at the `-t` option to have more things done in parallel (if your system has enough threads available), or the `-x` option to play around with the exploration level, which is a way to set the trade-off between quality and computing time.

**Comment by IsaacDm** [comment] 2020-04-24 17:08
I'm having more than 150 vehicles starting from various locations and serving jobs at close to 40000 locations. When I'm trying to generate matrix with the 'add_osrm_matrix.py', it throws a KeyError: 'durations'

But when i reduce the count of vehicles and jobs, the matrix is generated without any problem.

**Comment by jcoupey** [comment] 2020-04-24 17:57
> serving jobs at close to 40000 locations

Ahah serious stuff then. I get it why you wish to pre-compute the matrix only once. The way the solving approach will scale in your case highly depends on how the problem and the constraints are set. For example if from each of the vehicles, most jobs are unreachable, then it will tend to speed-up things.

> When I'm trying to generate matrix with the 'add_osrm_matrix.py', it throws a KeyError: 'durations'

My guess is that you're going over the max size that your OSRM instance will handle, hence an error message without a `durations` key. If you're using `osrm-routed`, you want to check the `--max-table-size` command-line arg.

The first bottleneck you may then encounter is the **huge** size of the json file containing the matrix...

Then what I'd do for this kind of problem size would be to start with a "light run" with only the heuristic and see how long that takes. This can be achieved by commenting out [this line](https://github.com/VROOM-Project/vroom/blob/0eb07fb64588ecbad61ab3c89a48329950b61440/src/problems/vrptw/vrptw.cpp#L191) if you have time windows, or [this line](https://github.com/VROOM-Project/vroom/blob/0eb07fb64588ecbad61ab3c89a48329950b61440/src/problems/cvrp/cvrp.cpp#L208) if you solve a CVRP. Then make sure to solve using `vroom -x 0`.

Another option, especially if your vehicles start from various locations, is to apply some pre-clustering to the problem.

Happy to have some feedback on your tests anyway.

**Comment by IsaacDm** [comment] 2020-04-24 18:12
Thanks for the detailed answer. Where can I find the --max-table-size command-line arg in the application?

**Comment by jcoupey** [comment] 2020-04-24 19:38
The 100 limit is the default on the `osrm-routed` side, that's what `--max-table-size` is for. See `osrm-routed -h` for all options.

**Comment by IsaacDm** [comment] 2020-04-27 13:31
I got it, thanks. I have been able to generate 2k*2k duration_matrix using add_osrm_matrix.py script. However, when I using ./bin/vroom to resolve the problem for optimized routes, it's throwing 
### "[Error] std::bad_alloc"

Apparently it is memory allocation exception with in the code. Could you please suggest a fix. Thank you

**Comment by jcoupey** [comment] 2020-04-27 17:05
This error indeed means you're reaching some limit while trying to allocate memory. The matrix seems like a good candidate for running into this kind of trouble but I'm surprised it happens with a "small" 2000*2000 matrix. Did you try smaller matrices? How much RAM do you have?

It's not really possible to do debugging without the input file, can you share it somehow? Or alternatively you might have some luck getting a backtrace using `gdb`.

**Comment by IsaacDm** [comment] 2020-04-28 08:15
I'm able to solve smaller matrices without any issue. Problems with bigger matrices are giving me {"code":1,"error":"std::bad_alloc"}. I have ram of total 256GB.

**Comment by jcoupey** [comment] 2020-04-28 08:36
Given your amount of RAM, there is probably something else happening. What I'd do in the first place would be:

- build `vroom` with debug symbols (replace `-O3` with `-O0 -g -ggdb` on [this line](https://github.com/VROOM-Project/vroom/blob/0eb07fb64588ecbad61ab3c89a48329950b61440/src/makefile#L8))
- run with `gdb` and get a backtrace of the error:

```bash
gdb vroom
run -i input_file.json
bt
```

**Comment by IsaacDm** [comment] 2020-04-28 09:05
> Given your amount of RAM, there is probably something else happening. What I'd do in the first place would be:
> 
> * build `vroom` with debug symbols (replace `-O3` with `-O0 -g -ggdb` on [this line](https://github.com/VROOM-Project/vroom/blob/0eb07fb64588ecbad61ab3c89a48329950b61440/src/makefile#L8))
> * run with `gdb` and get a backtrace of the error:
> 
> ```shell
> gdb vroom
> run -i input_file.json
> bt
> ```

I will try this and update you. Thanks

**Comment by IsaacDm** [comment] 2020-04-28 11:28
> This error indeed means you're reaching some limit while trying to allocate memory. The matrix seems like a good candidate for running into this kind of trouble but I'm surprised it happens with a "small" 2000*2000 matrix. Did you try smaller matrices? How much RAM do you have?
> 
> It's not really possible to do debugging without the input file, can you share it somehow? Or alternatively you might have some luck getting a backtrace using `gdb`.

Here is my input file:

https://techwaveinc-my.sharepoint.com/:f:/g/personal/isaac_dm_techwave_net/Eot3l4ulWSBOkUOufuRcZmUB7JVTq0pG8cQRSC9BV7eu2w?e=vbi5qA

**Comment by jcoupey** [comment] 2020-04-28 13:09
Unfortunately I'm unable to download the above file. The download from the website always randomly stops at some point, not reaching the total size of the file, and I get a truncated file...

**Comment by IsaacDm** [comment] 2020-04-28 17:13
I'm unable to build it with the suggested modifications. Getting the following error:
make
mkdir -p ../bin
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O0 -g -ggdb -o ../bin/vroom main.o algorithms/munkres.o algorithms/kruskal.o algorithms/local_search/operator.o algorithms/local_search/local_search.o algorithms/heuristics/solomon.o routing/ors_wrapper.o routing/osrm_routed_wrapper.o routing/http_wrapper.o problems/vrp.o problems/cvrp/cvrp.o problems/vrptw/vrptw.o problems/tsp/tsp.o problems/cvrp/operators/intra_or_opt.o problems/cvrp/operators/intra_mixed_exchange.o problems/cvrp/operators/or_opt.o problems/cvrp/operators/reverse_two_opt.o problems/cvrp/operators/mixed_exchange.o problems/cvrp/operators/intra_relocate.o problems/cvrp/operators/pd_shift.o problems/cvrp/operators/relocate.o problems/cvrp/operators/route_exchange.o problems/cvrp/operators/intra_cross_exchange.o problems/cvrp/operators/exchange.o problems/cvrp/operators/two_opt.o problems/cvrp/operators/cross_exchange.o problems/cvrp/operators/intra_exchange.o problems/vrptw/operators/intra_or_opt.o problems/vrptw/operators/intra_mixed_exchange.o problems/vrptw/operators/or_opt.o problems/vrptw/operators/reverse_two_opt.o problems/vrptw/operators/mixed_exchange.o problems/vrptw/operators/intra_relocate.o problems/vrptw/operators/pd_shift.o problems/vrptw/operators/relocate.o problems/vrptw/operators/route_exchange.o problems/vrptw/operators/intra_cross_exchange.o problems/vrptw/operators/exchange.o problems/vrptw/operators/two_opt.o problems/vrptw/operators/cross_exchange.o problems/vrptw/operators/intra_exchange.o problems/tsp/heuristics/christofides.o problems/tsp/heuristics/local_search.o structures/generic/matrix.o structures/generic/edge.o structures/generic/undirected_graph.o structures/vroom/job.o structures/vroom/tw_route.o structures/vroom/raw_route.o structures/vroom/vehicle.o structures/vroom/time_window.o structures/vroom/solution_state.o structures/vroom/location.o structures/vroom/input/input.o structures/vroom/solution/summary.o structures/vroom/solution/route.o structures/vroom/solution/step.o structures/vroom/solution/computing_times.o structures/vroom/solution/solution.o structures/cl_args.o utils/output_json.o utils/exception.o utils/input_parser.o utils/version.o /usr/lib64/libboost_system.so.1.53.0 -lpthread -lssl -lcrypto
g++: error: unrecognized command line option ‘-std=c++17’
make: *** [../bin/vroom] Error 1

**Comment by jcoupey** [comment] 2020-04-28 17:29
> g++: error: unrecognized command line option ‘-std=c++17’

This is not related to the changes you've performed but probably to the fact that you have a `g++` version that does not support this flag. You can either:

- use a more recent version of `g++`
- checkout the latest VROOM release `v1.6.0`, it's still using c++14

**Comment by IsaacDm** [comment] 2020-04-29 10:47
[‎4/‎29/‎2020 3:30 PM]  
No Title 
(gdb) run -i fot_bu_matrix_2k.json -o fot_bu_matrix_2k_output.json
Starting program: /home/centos/vroomApp/vroom/bin/vroom -i fot_bu_matrix_2k.json -o fot_bu_matrix_2k_output.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Error] std::bad_alloc
[Inferior 1 (process 10507) exited with code 01]
Missing separate debuginfos, use: debuginfo-install boost-system-1.53.0-27.el7.x86_64 glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64
(gdb)

**Comment by jcoupey** [comment] 2020-04-29 13:28
You should get additional info when asking for a backtrace of the error (`bt` instruction on the last `(gdb)` prompt).

**Comment by IsaacDm** [comment] 2020-04-30 09:42
[centos@ip-172-31-25-171 ~]$ cd vroomApp/vroom/bin
[centos@ip-172-31-25-171 bin]$ gdb vroom
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-119.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/centos/vroomApp/vroom/bin/vroom...done.
(gdb) run -i fot_bu_matrix_2k.json
Starting program: /home/centos/vroomApp/vroom/bin/vroom -i fot_bu_matrix_2k.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Error] std::bad_alloc
{"code":1,"error":"std::bad_alloc"}
[Inferior 1 (process 10568) exited with code 01]
Missing separate debuginfos, use: debuginfo-install boost-system-1.53.0-27.el7.x86_64 glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64
(gdb) bt
No stack.
(gdb)

**Comment by jcoupey** [comment] 2020-04-30 09:55
> Missing separate debuginfos, use: debuginfo-install boost-system-1.53.0-27.el7.x86_64 glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64

You're missing stuff to do effective debugging. Looks like you need to do something similar as in the first answer of [this SO post](https://stackoverflow.com/questions/10389988/missing-separate-debuginfos-use-debuginfo-install-glibc-2-12-1-47-el6-2-9-i686).

**Comment by IsaacDm** [comment] 2020-04-30 13:11
Hi @jcoupey, I think I have fix the issue with in the add_osrm_matrix.py code and generated a new input table of various sizes ranging from 200 to 2000. VROOM is able to solve 200 table matrix in few seconds, 400 in less than a minute and 1000,1200 size matrices took more than 20 minutes to solve. Now I'm running 2k*2k and it has been running for the past 1.5 hours - no result yet.

Is there a way to speed up this solution? Following is my server configuration on AWS cloud.
1. R5*8
2. OS: CentOS7
3. CPUs: 32
4. RAM: 256

If this server is not enough, kindly suggest the size I have to scale up to. Thanks

**Comment by jcoupey** [comment] 2020-04-30 13:58
> I think I have fixed the issue - in the add_osrm_matrix.py code,

You mean you fixed the `std::bad_alloc` error? Could you expand a bit on how you did it, because this is maybe something we can use to improve error handling.

**Comment by IsaacDm** [comment] 2020-04-30 14:29
> > I think I have fixed the issue - in the add_osrm_matrix.py code,
> 
> You mean you fixed the `std::bad_alloc` error? Could you expand a bit on how you did it, because this is maybe something we can use to improve error handling.

Firstly, add_osrm_matrix.py file wasn't able to generate duration_matrix. It was throwing JSON_serializable error. I fixed it by modifying the code as the following:
Old: data['matrix'].append(map(lambda d: round_to_cost(d), line))
New:  data['matrix'].append([round_to_cost(d) for d in line])

Later, I have observed that if the duration between two locations would be returned as 'None' if there is no route available between them, code will fail at round_to_cost() method. This I have handled it with the following:

  for line in matrix:
    line_list= []
    for d in line:
      try:
        f = round_to_cost(d)
        line_list.append(f)
      except:
        line_list.append(172800)
    data['matrix'].append(line_list)

Initially, when I have generated my duration_matrix, using my above modifications, the matrix was wrongly generated by appending the list continuously and not as a new list. But the VROOM application was generating std::bad_alloc instead of input error. But now the input duration_matrix is generated properly by add_osrm_matrix and VROOM application is able to give us the optimum routes.

However, like I said in the above comment, the VROOM application is taking 2 hours to give a solution for 2k*2K. We have to find some parallelism here to use it for our actual problem.

**Comment by jcoupey** [comment] 2020-04-30 15:12
Thanks for the further information. So if I get it correctly, `vroom` was unable to issue a clear error when inputting a matrix with incorrect size/structure? Then we should fix this. We normally have checks for matrix line sizes and I don't seem to be able to reproduce the error. Could you share a small reproducible example now that you understood the problem?

> We have to find some parallelism here to use it for our actual problem.

There are two built-in parameters you want to try out (see `vroom -h` or [the docs](https://github.com/VROOM-Project/vroom/wiki/Usage#complete-usage-and-options-list-for-v160)):

- `-t` in order to specify the number of threads you can allocate to the search
- `-x` to set the trade-off between solution quality and computing time

To go for the fastest solution, you'd use `-t 32 -x 0` if 32 is the number of threads you can use concurrently.

**Comment by IsaacDm** [comment] 2020-04-30 17:06
Thanks a lot! 32 threads have brought the processing time to less than 15 min. But I need it way too much faster. Because my full scaled matrix would be of 40k*40K size and I need to iterate this process multiple times.

Thanks again for you support!

**Comment by jcoupey** [comment] 2020-04-30 19:11
The number of threads depends on your setting, you may want to monitor activity while solving using a tool like `htop` to see how CPU resources are used.

For a 2000 location instance, 15 minutes is suspiciously long, especially if you throw 32 threads at it. What value of `-x` have you been using? Also did you recompile `vroom` with `-O3` after your previous tests?

**Comment by IsaacDm** [comment] 2020-04-30 19:22
> The number of threads depends on your setting, you may want to monitor activity while solving using a tool like `htop` to see how CPU resources are used.
> 
> For a 2000 location instance, 15 minutes is suspiciously long, especially if you throw 32 threads at it. What value of `-x` have you been using? Also did you recompile `vroom` with `-O3` after your previous tests?

command: ./bin/vroom -t 32 -x 0 -i inputfile -o outputfile

Yes, I have created a new instance of VROOM instance and running it. The other instance with the changes in makefile is still available.

**Comment by jcoupey** [comment] 2020-04-30 19:53
There is always a point where the computing times will go wild when the problem size increases.

But from my experience the computing times you report look a bit too long for the problem size. Could you share a problem instance you've solved that is over 1K locations so we can run some comparisons?

**Comment by IsaacDm** [comment] 2020-04-30 19:56
https://techwaveinc-my.sharepoint.com/:f:/g/personal/isaac_dm_techwave_net/Eot3l4ulWSBOkUOufuRcZmUB7JVTq0pG8cQRSC9BV7eu2w?e=NV0NSW

**Comment by IsaacDm** [comment] 2020-04-30 19:56
> There is always a point where the computing times will go wild when the problem size increases.
> 
> But from my experience the computing times you report look a bit too long for the problem size. Could you share a problem instance you've solved that is over 1K locations so we can run some comparisons?

https://techwaveinc-my.sharepoint.com/:f:/g/personal/isaac_dm_techwave_net/Eot3l4ulWSBOkUOufuRcZmUB7JVTq0pG8cQRSC9BV7eu2w?e=NV0NSW

**Comment by IsaacDm** [comment] 2020-05-01 07:44
Have you been able to download the data?

**Comment by jcoupey** [comment] 2020-05-01 08:31
> after we include these constraints VROOM is going to take exponentially more longer time to give the result.

Quite the opposite in fact. I solved your instance in ~11 minutes using `-t 4 -x 0`. The reason it takes so long for `vroom` to solve it is precisely because there is absolutely no timing constraint. Every single job is a candidate for every vehicle: going across the country and back is **valid**, even if such a solution would not make any sense. As a result, our local search phase does far too many lookups for options that are valid but useless.

As a general rule of thumb, setting more constraints will narrow the solution space and cause the solving to converge faster. If I simply add a `time_window:[0, 100000]` key for each vehicle, then I get a solution in 3 seconds (!!) using `-t 4 -x 0`. This is because internally we rule out jobs/vehicles combinations that involve jobs that are too far away from a given vehicle to meet this time window.

**Comment by IsaacDm** [comment] 2020-05-01 08:35
> > after we include these constraints VROOM is going to take exponentially more longer time to give the result.
> 
> Quite the opposite in fact. I solved your instance in ~11 minutes using `-t 4 -x 0`. The reason it takes so long for `vroom` to solve it is precisely because there is absolutely no timing constraint. Every single job is a candidate for every vehicle: going across the country and back is **valid**, even if such a solution would not make any sense. As a result, our local search phase does far too many lookups for options that are valid but useless.
> 
> As a general rule of thumb, setting more constraints will narrow the solution space and cause the solving to converge faster. If I simply add a `time_window:[0, 100000]` key for each vehicle, then I get a solution in 3 seconds (!!) using `-t 4 -x 0`. This is because internally we rule out jobs/vehicles combinations that involve jobs that are too far away from a given vehicle to meet this time window.

That really helped and gave me confidence. Thank you. I will try with constraints in place and update you.

**Comment by IsaacDm** [comment] 2020-05-03 08:22
Hi, how do I put a time constraint of 10 hours maximum for a any vehicle to perform jobs. 10 hours is included of travel time and service time. I have tried multiple ways but everytime, the total duration of trip is exceeding 10 hours (36000). Thank you

**Comment by IsaacDm** [comment] 2020-05-13 13:24
Hi @jcoupey , it wasn't possible to solve 40K*40K at once. So we have divided the locations into 12 clusters and are running the optimized routes. VROOM is successfully delivering the job.

However, when it comes to priority, we are having problems. Seems like VROOM is not honoring "Priority" Constraint. For normal jobs we have given 'Priority': 0 and for mandatory jobs to be completed on that day we set 'Priority': 1. We observed that few of the Priorities are only addressed while the rest are being skipped.

We tried to solve this priority constraint with smaller instance, it was working absolutely fine. But with larger instances, we are having this no honoring priority issue.

Could you please help us if we are doing in the right way.

Thanks!

**Comment by jcoupey** [comment] 2020-05-14 10:02
Internally, the priorities are treated as an optimization objective, so basically we try our best to maximize the sum of priorities over all assigned jobs, then minimize overall travel time. As a result:

- I would not expect the various modelling combinations you tried to significantly change the behaviour;
- there is no strong guarantee that all high priority jobs will be included. So the fact that it works absolutely fine on smaller instances but is less efficient with huge instances is probably due to some limitation of the current implementation.

On the later, you may be hitting something similar to #319. It would be useful if you could share a standalone instance to confirm.

**Comment by jcoupey** [comment] 2020-06-11 10:05
Closing as stale, feel free to reopen if required.

**Closed by jcoupey** 2020-06-11 10:05 UTC
Labels: discussion
