### ISSUE TITLE
capacity/amount issue

### ISSUE THREAD

**Issue by atisnz** [VROOM-Project/vroom#238] opened 2019-06-10 04:38 UTC
Hi,
I'm getting an "Invalid amount value." when trying to solve the attached json file on your demo website. 
test2.json.txt](https://github.com/VROOM-Project/vroom/files/3270569/test2.json.txt)

Once removed the capacity/amount, the solver worked. not sure, if the results are supposed to be like attached, but service and waiting_time values are all 0.  See the results file.
[res.json.txt](https://github.com/VROOM-Project/vroom/files/3270572/res.json.txt)
Would be possible to include mandatory rest time to the trip? 
Our drivers must take 30mins  after driving 5.5hours ; they can repeat that once again the same day.  
Thanks

**Comment by jcoupey** [comment] 2019-06-10 07:14
The "invalid amount value" error happens [here](https://github.com/VROOM-Project/vroom/blob/ce5c7135dd977748e3a784168dbd7708001eafdd/src/utils/input_parser.cpp#L63-L66) because you provide non-integer amounts. What you could do is decide on a number of digits and multiply all your values by `10^n` to have integer amounts/capacities.

You'll get the same kind of parsing error with non-integers service times. Services times will show up in the output as soon as you provide them as integers.

> waiting_time values are all 0

Here waiting times are 0 because there is no reason to wait at any point in the routes based on the time windows constraints.

> Would be possible to include mandatory rest time to the trip?

We have a ticket tracking the implementation of breaks (see https://github.com/VROOM-Project/vroom/issues/186).

**Comment by atisnz** [comment] 2019-06-11 02:25
Thanks, that worked. 
I have another problem: when I load the attached request, some sites are coming up black on the map and they are not showing in the result either. Could you pls advise why is that? Thanks!
[test2.json.txt](https://github.com/VROOM-Project/vroom/files/3274504/test2.json.txt)

**Comment by jcoupey** [comment] 2019-06-11 07:44
In the frontend, positions that are shown in black after solving are unassigned jobs. Those show up in the `unassigned` array in the [json response](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#output).

This happens when including the jobs would make the solution invalid with regard to some of the constraints imposed in the input problem (skills, capacity, time windows etc.). In your example, there is a single vehicle with a capacity of `6000` while the sum of all job amounts is `11360`.

In a situation like this, we try to maximize the number of jobs included in the solution, then minimize overall travel time.

**Comment by atisnz** [comment] 2019-06-11 11:45
Yes, I found those in the unassigned part, I just didn't know why did they get there.
One last question. Would you know about anyone who compiled the project on windows?
Thanks

**Comment by nilsnolde** [comment] 2019-06-11 11:57
I wouldn't go through the pain of trying to set up anything on windows which was intended and developed for Linux. Try the built-in Linux subsystem, which all modern Win distros support these days, e.g. https://virtualizationreview.com/articles/2018/06/13/installing-wsl-on-windows-server.aspx

**Comment by jcoupey** [comment] 2019-06-11 12:27
The only record of building on windows so far is https://github.com/VROOM-Project/vroom/issues/207. There may be other windows users we're not aware of though as we're most likely to have feedback on building problems than successful builds. ;-)

**Comment by atisnz** [comment] 2019-06-12 01:59
We have a customer running exclusively windows environment that's why we would prefer windows solution. We trying to visualise our customers trucks routes in Qgis and produce more optimal routes. We have been using the demo server so far and its produced the most promising results.   
Anyway... I have more questions. When using time_windows sometimes we get some waiting times.  How would be possible to eliminate these waiting times?
Also I have noticed, that the arrival times are not calculated correctly, see attached. I reckon the next job arrival time should be the previous + service_time + duration.

**Comment by atisnz** [comment] 2019-06-12 02:07
Forgot the files:
[tw_res1.txt](https://github.com/VROOM-Project/vroom/files/3279269/tw_res1.txt)
[tw_req1.txt](https://github.com/VROOM-Project/vroom/files/3279270/tw_req1.txt)

**Comment by jcoupey** [comment] 2019-06-12 07:22
> How would be possible to eliminate these waiting times?

Waiting times are a direct consequence of the time windows constraints you setup. In your example, removing the waiting time for job 14 would mean arriving later, but then job 10 would be unassigned as it's already done at the latest possible time (ETA 25200 and due at that time). If you push forward the due date for job 10, then the waiting time will decrease.

> Also I have noticed, that the arrival times are not calculated correctly

Can you point out a specific example from your file?

**Comment by atisnz** [comment] 2019-06-12 08:19
from the tw_res1 file, the first 2 jobs:
{
					"type": "job",
					"location": [174.7572926,-36.78278],
					"job": 0,
					"service": 150,
					"waiting_time": 0,
					"arrival": 22918,
					"duration": 1275,
					"distance": 18696
				},
				{
					"type": "job",
					"location": [174.7552645,-36.7803657],
					"job": 1,
					"service": 126,
					"waiting_time": 0,
					"arrival": 23161,  **>>>> this should be 22918+150+1368 = 24436‬**
					"duration": 1368,
					"distance": 19228
				},

**Comment by jcoupey** [comment] 2019-06-12 12:58
> "arrival": 23161, >>>> this should be 22918+150+1368 = 24436‬

The `duration` key at step level works like the `distance` value, it's a **cumulated** value from the start of the route, see the [step description](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#steps) for more.

Here the travel time from job 0 to job 1 is 1368 - 1275 = 93 based on the `duration` keys, or 23161 - 22918 - 150 = 93 based on arrival and service times.

**Comment by atisnz** [comment] 2019-06-13 05:00
That makes sense. Thanks for the clarification... 
> Waiting times are a direct consequence of the time windows constraints you setup. In your example, removing the waiting time for job 14 would mean arriving later, but then job 10 would be unassigned as it's already done at the latest possible time (ETA 25200 and due at that time). If you push forward the due date for job 10, then the waiting time will decrease.
> 
From this it sounds, that you create the shortest path first and then appropriate start time is selected to best fit the time windows constraints + some wait time is applied where its necessary.
In the above example the wait time was around 48mins which is a very long time. 
Unfortunately the time windows are set by the customers, so they cannot be changed. Would be any other way to eliminate the waiting time (eg dropping the site and pick it up on the way back) or somehow to set the acceptable max waiting time?
The last issue we have, is that despite of early (4AM) start time set for the vehicle the solution has start time set after 6AM only. Any way to force earlier time? I did set a shorter time window for the vehicle, but sites were unasigned rather than the start time pushed forward. Thanks!

**Comment by jcoupey** [comment] 2019-06-13 10:55
> From this it sounds, that you create the shortest path first and then appropriate start time is selected to best fit the time windows constraints + some wait time is applied where its necessary.

We search for a short path **while ensuring validity constraints**. For time windows constraints, we actually don't decide the exact arrival time during the search, but we maintain validity margins (earliest and latest arrival times). Then after solving, we choose valid arrival/start times in order to:

- arrive asap at the latest step
- start as late as possible at the first step in order to minimize waiting times along the route

Again it's quite common to have tight and/or disjoints time windows for jobs resulting in longer trips, waiting times, or unassigned jobs.

> dropping the site and pick it up on the way back

You can force a later arrival at this job by changing its earliest service time from the time window. Note that this will probably increase the total travel time, which is the reason why we didn't do it in the first place.

> the vehicle has start time set after 6AM only

What happens here is that:

- starting earlier with the current job ordering would not make sense (it would just increase waiting times along the route)
- changing the ordering (e.g. to start with all non time-constrained jobs then come back for others) would likely be more expensive so we don't do it.

If you really need a different, more expensive solution, it means that some constraints are missing or too loose. I see basically two options:

1. shorten the vehicle time window by advancing it's end time (but not too much so "late" jobs don't get unassigned)
2. force the vehicle to work early by imposing an early due date to some jobs

**Comment by jcoupey** [comment] 2019-08-05 10:14
Closing here, feel free to reopen if required.

**Closed by jcoupey** 2019-08-05 10:14 UTC
Labels: question
