### ISSUE TITLE
OSRM has unfound route(s) error

### ISSUE THREAD

**Issue by KieCap** [VROOM-Project/vroom#190] opened 2018-12-19 15:29 UTC
Can you give me some information on what would cause the following error: 

`code 1: OSRM has unfound route(s) fromlocation [-2.437567;50.545750]`

Some more example coordinates:

```
[-2.450658;50.541842]
[-2.445157;50.566722]
[-2.446163;50.562137]
[-2.116702;51.454823] 
```

**Comment by jcoupey** [comment] 2018-12-20 11:10
The first step we take after loading the problem description is to fire an OSRM `table` request to get the travel cost from/to any point in the problem. If for some reason OSRM can't find a route between some of the points, the corresponding entry in the returned matrix will be `null`. This is expected behaviour from the OSRM point of view. The reason we stop computing altogether in that case is that we have no way to decide how those locations could fit in the solution because some costs are impossible to evaluate.

The tricky part is that this is highly related to the way OSRM snaps the provided coordinates to the road network. Sometimes just slightly moving a "wrong" pair of coordinates will fix the problem...

I remember this used to happen much more with older versions of OSRM and much less now, due to improved snapping strategies. So a first step would be to make sure you're running a recent version.

A real fix to prevent this from happening would be to take advantage of https://github.com/Project-OSRM/osrm-backend/pull/5257. In that case we should be aware that some of the costs used while solving may be only estimates and probably investigate a bit more on the impact.

**Comment by KieCap** [comment] 2019-01-02 11:08
@jcoupey happy new year! :confetti_ball: 

It appears that the issue is only happening when I send points to VROOM that are in the sea (the English Channel specifically in my sample data). This goes along with what you're saying, in that OSRM does not know how to route to those points.

As the GPS information is user-generated, I'll need to come up with some way to filter these out before sending to VROOM. 

Thanks for your help.

**Comment by jcoupey** [comment] 2019-02-13 16:21
Closing here as it seems to come down to filtering out input data. Feel free to re-open if required.

**Closed by jcoupey** 2019-02-13 16:21 UTC
Labels: question
