### ISSUE TITLE
Do all jobs at same location together

### ISSUE THREAD

**Issue by jensbe74** [VROOM-Project/vroom#337] opened 2020-05-02 17:42 UTC
It would be good if we have a switch that can be used to determine that all jobs in one location have to be done together if it fits the time Windows.
At the moment it is so that if I have 100 jobs, for example 10 jobs at one address and 5 at another. These jobs are torn apart and the address is approached several times.  Sometimes even from several vehicle.

**Comment by jcoupey** [comment] 2020-05-05 08:50
I don't really see this as a new feature, as one should expect the optimization to do just this whenever it's both possible and cheaper. But the way the solving approach works makes it more difficult to handle numerous jobs at the same place. For example we have simple operators to try moving one job or two consecutive jobs from one route to another. But as soon as you have more that three jobs in a row we don't check globally moving them *together* exhaustively.

Now if you have several jobs that **must** be handled together, then my advice is to bundle them anyway into one single job prior to optimization. This will: 1. help on the solving side as dealing with a single job is more efficient (see above) ; 2. reduce problem size, thus computing times ; 3. avoid embarrassing situations where they are split!

On the other hand it's totally valid to have same-location jobs with say different time windows. Then there are basically two options if they're not done together:

- it makes sense to tear them apart because it's valid and doing so enables another gain elsewhere in the route plan ;
- it would be cheaper to have them bundled, in which case the solving is at stake.

If you run into the later, please provide a reproducible example so we can dig in.

**Comment by jensbe74** [comment] 2020-05-06 19:32
For example, if you only have one vehicle with several time windows (for several days) and you have several jobs without time Windows and some of them are in the same location, these are spread over different time slots.  I can not imagine somehow that it makes sense to go to an address at multiple time Windows. But that happens

**Comment by jcoupey** [comment] 2020-05-07 12:03
Could you provide a reproducible example for this behaviour?

**Comment by jensbe74** [comment] 2020-05-13 11:11
Can I send you an email with the example? I don't want to post the data here.

**Comment by jcoupey** [comment] 2020-05-13 11:52
@jensbe74 yes you can use contact@verso-optim.com.

**Comment by jcoupey** [comment] 2020-05-14 17:08
@jensbe74 from the examples you shared, the results you get are expected for two reasons:

- the limiting factor for including more jobs is always the vehicle time window
- you have a lot of jobs that have duplicated locations.

So it happens that because of the limited working hours, we're not able to add more jobs due to their service time, even if other jobs at the same locations are included in the solution. You should rather see this as: "it would be too long to perform all jobs at location X, but we still managed to fit some of them in". Again this is expected as we try to maximize the number of assigned jobs.

If the resulting solution is not meaningful for you, my advice would be to bundle the various tasks at the same location into a single job prior to optimization, and adjust overall service time accordingly (see previous comments).

**Comment by jensbe74** [comment] 2020-05-16 19:15
Hi Julien To summarize the jobs beforehand would be a possibility.  However, I am of the opinion that the system should actually do it itself since there is no better solution from the cost side.  No drive and the job is done.  So I wonder if there isn't a bug?  It shouldn't matter how many jobs are in the same location.  These would always have to be processed one after the other - no matter how many.  Provided, of course, it fits into the vehicle's time window.  In my example, that was definitely possible.

**Comment by jcoupey** [comment] 2020-05-17 19:54
> Provided, of course, it fits into the vehicle's time window

My point is precisely that it's not possible in the example you shared. The vehicle has a `time_window: [547200, 581400]` and in the solution, it's start and end arrivals are respectively `547200` and `581188`. So no matter if they don't increase travel time, no other unassigned job can fit in, because they have a `service` time of `1188`.

Because of the service times, the only way to fit all jobs from the list you pointed out would be to discard some other jobs. And then because many jobs happen at the same location, you'd probably face the same problem elsewhere.

**Comment by jcoupey** [comment] 2020-06-11 10:06
Closing as this seems to have been answered. Feel free to reopen if required.

**Closed by jcoupey** 2020-06-11 10:06 UTC
Labels: question
