### ISSUE TITLE
Facing error  :- {"code":2,"error":"Invalid value. (offset: 0)"}

### ISSUE THREAD

**Issue by prince4249** [VROOM-Project/vroom#534] opened 2021-06-18 07:22 UTC
I am providing the input file for your reference -

{
    "vehicles":[
        {
            "id":10,
            "start_index":0,
            "end_index":0,
            "capacity":[
                50000000
            ],
            "time_window":[
                0,
                28800
            ]
        },
        {
            "id":11,
            "start_index":0,
            "end_index":0,
            "capacity":[
                50000000
            ],
            "time_window":[
                0,
                28800
            ]
        },
        {
            "id":12,
            "start_index":0,
            "end_index":0,
            "capacity":[
                50000000
            ],
            "time_window":[
                0,
                28800
            ]
        },
        {
            "id":13,
            "start_index":0,
            "end_index":0,
            "capacity":[
                50000000
            ],
            "time_window":[
                0,
                28800
            ]
        },
        {
            "id":14,
            "start_index":0,
            "end_index":0,
            "capacity":[
                50000000
            ],
            "time_window":[
                0,
                28800
            ]
        },
        {
            "id":15,
            "start_index":0,
            "end_index":0,
            "capacity":[
                50000000
            ],
            "time_window":[
                0,
                28800
            ]
        }
    ],
    "jobs":[
        {
            "id":10,
            "location_index":1,
            "delivery":[
                26000000
            ],
            "service":1800
        },
        {
            "id":11,
            "location_index":2,
            "delivery":[
                10700000
            ],
            "service":1800
        },
        {
            "id":12,
            "location_index":3,
            "delivery":[
                10000000
            ],
            "service":1800
        },
        {
            "id":13,
            "location_index":4,
            "delivery":[
                7300000
            ],
            "service":1800
        },
        {
            "id":14,
            "location_index":5,
            "delivery":[
                10000000
            ],
            "service":1800
        },
        {
            "id":15,
            "location_index":6,
            "delivery":[
                10000000
            ],
            "service":1800
        },
        {
            "id":16,
            "location_index":7,
            "delivery":[
                16000000
            ],
            "service":1800
        },
        {
            "id":17,
            "location_index":8,
            "delivery":[
                5000000
            ],
            "service":1800
        },
        {
            "id":18,
            "location_index":9,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":19,
            "location_index":10,
            "delivery":[
                1050000
            ],
            "service":1800
        },
        {
            "id":20,
            "location_index":11,
            "delivery":[
                2950000
            ],
            "service":1800
        },
        {
            "id":21,
            "location_index":12,
            "delivery":[
                2600000
            ],
            "service":1800
        },
        {
            "id":22,
            "location_index":13,
            "delivery":[
                2000000
            ],
            "service":1800
        },
        {
            "id":23,
            "location_index":14,
            "delivery":[
                3000000
            ],
            "service":1800
        },
        {
            "id":24,
            "location_index":15,
            "delivery":[
                3800000
            ],
            "service":1800
        },
        {
            "id":25,
            "location_index":16,
            "delivery":[
                1000000
            ],
            "service":1800
        },
        {
            "id":26,
            "location_index":17,
            "delivery":[
                1500000
            ],
            "service":1800
        },
        {
            "id":27,
            "location_index":18,
            "delivery":[
                1000000
            ],
            "service":1800
        },
        {
            "id":28,
            "location_index":19,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":29,
            "location_index":20,
            "delivery":[
                1400000
            ],
            "service":1800
        },
        {
            "id":30,
            "location_index":21,
            "delivery":[
                1000000
            ],
            "service":1800
        },
        {
            "id":31,
            "location_index":22,
            "delivery":[
                1500000
            ],
            "service":1800
        },
        {
            "id":32,
            "location_index":23,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":33,
            "location_index":24,
            "delivery":[
                1500000
            ],
            "service":1800
        },
        {
            "id":34,
            "location_index":25,
            "delivery":[
                1000000
            ],
            "service":1800
        },
        {
            "id":35,
            "location_index":26,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":36,
            "location_index":27,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":37,
            "location_index":28,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":38,
            "location_index":29,
            "delivery":[
                2500000
            ],
            "service":1800
        },
        {
            "id":39,
            "location_index":30,
            "delivery":[
                1000000
            ],
            "service":1800
        },
        {
            "id":40,
            "location_index":31,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":41,
            "location_index":32,
            "delivery":[
                2000000
            ],
            "service":1800
        },
        {
            "id":42,
            "location_index":33,
            "delivery":[
                2600000
            ],
            "service":1800
        },
        {
            "id":43,
            "location_index":34,
            "delivery":[
                1700000
            ],
            "service":1800
        },
        {
            "id":44,
            "location_index":35,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":45,
            "location_index":36,
            "delivery":[
                2500000
            ],
            "service":1800
        },
        {
            "id":46,
            "location_index":37,
            "delivery":[
                4500000
            ],
            "service":1800
        },
        {
            "id":47,
            "location_index":38,
            "delivery":[
                500000
            ],
            "service":1800
        },
        {
            "id":48,
            "location_index":39,
            "delivery":[
                1800000
            ],
            "service":1800
        },
        {
            "id":49,
            "location_index":40,
            "delivery":[
                5200000
            ],
            "service":1800
        }
    ],
    "matrices":{
        "car":{
            "durations":[
                [
                    0,
                    1162,
                    1285,
                    1066,
                    798,
                    2559,
                    241,
                    2025,
                    876,
                    2158,
                    1224,
                    1741,
                    811,
                    2934,
                    2032,
                    1970,
                    1899,
                    1012,
                    717,
                    1079,
                    2196,
                    2481,
                    913,
                    1269,
                    2546,
                    2377,
                    1397,
                    1877,
                    604,
                    1166,
                    1732,
                    1131,
                    531,
                    1571,
                    1031,
                    1489,
                    1191,
                    933,
                    1678,
                    1982,
                    1273
                ],
                [
                    1188,
                    0,
                    732,
                    726,
                    844,
                    1519,
                    1093,
                    1263,
                    1762,
                    1327,
                    975,
                    869,
                    1094,
                    2333,
                    1743,
                    1139,
                    1610,
                    410,
                    605,
                    252,
                    1907,
                    1441,
                    352,
                    1362,
                    1993,
                    1777,
                    355,
                    1588,
                    872,
                    1572,
                    1132,
                    975,
                    1317,
                    760,
                    162,
                    1230,
                    932,
                    1680,
                    565,
                    1329,
                    1081
                ],
                [
                    1241,
                    738,
                    0,
                    1134,
                    1213,
                    1302,
                    1146,
                    818,
                    1696,
                    1066,
                    431,
                    1656,
                    1416,
                    1727,
                    1089,
                    865,
                    955,
                    782,
                    927,
                    607,
                    1253,
                    1600,
                    702,
                    883,
                    1339,
                    1170,
                    1007,
                    934,
                    805,
                    1980,
                    525,
                    431,
                    1250,
                    1453,
                    607,
                    1638,
                    1340,
                    1614,
                    1288,
                    2453,
                    1488
                ],
                [
                    1188,
                    713,
                    1124,
                    0,
                    497,
                    2168,
                    1053,
                    1912,
                    1939,
                    1976,
                    1366,
                    1043,
                    852,
                    2773,
                    2135,
                    1788,
                    2002,
                    408,
                    634,
                    815,
                    2299,
                    2090,
                    605,
                    1713,
                    2385,
                    2216,
                    945,
                    1980,
                    1048,
                    993,
                    1571,
                    1367,
                    1493,
                    630,
                    579,
                    651,
                    353,
                    1857,
                    964,
                    1144,
                    502
                ],
                [
                    806,
                    879,
                    1187,
                    372,
                    0,
                    2334,
                    666,
                    2078,
                    2258,
                    2141,
                    1399,
                    1211,
                    466,
                    2836,
                    2198,
                    1954,
                    2065,
                    505,
                    496,
                    946,
                    2362,
                    2256,
                    581,
                    1574,
                    2448,
                    2280,
                    1110,
                    2043,
                    910,
                    607,
                    1635,
                    1310,
                    1355,
                    1041,
                    745,
                    795,
                    497,
                    1718,
                    1123,
                    1288,
                    373
                ],
                [
                    2617,
                    1528,
                    1292,
                    2243,
                    2400,
                    0,
                    2521,
                    670,
                    2850,
                    306,
                    1585,
                    1699,
                    2676,
                    1728,
                    1686,
                    387,
                    1537,
                    1926,
                    2187,
                    1600,
                    1850,
                    618,
                    1962,
                    2037,
                    1618,
                    973,
                    1321,
                    1301,
                    1960,
                    3063,
                    1166,
                    1586,
                    2405,
                    1992,
                    1678,
                    2720,
                    2422,
                    2768,
                    1331,
                    2267,
                    2571
                ],
                [
                    241,
                    1115,
                    1140,
                    1081,
                    682,
                    2513,
                    0,
                    1880,
                    1918,
                    2111,
                    1263,
                    1614,
                    353,
                    2789,
                    2150,
                    1924,
                    2017,
                    885,
                    590,
                    1032,
                    2315,
                    2435,
                    866,
                    1308,
                    2401,
                    2232,
                    1351,
                    1996,
                    644,
                    925,
                    1587,
                    1171,
                    1088,
                    1444,
                    984,
                    1484,
                    1186,
                    1452,
                    1525,
                    1977,
                    1032
                ],
                [
                    2092,
                    1275,
                    808,
                    1869,
                    1948,
                    573,
                    1997,
                    0,
                    2367,
                    560,
                    989,
                    1717,
                    2151,
                    1408,
                    1383,
                    383,
                    1234,
                    1517,
                    1662,
                    1050,
                    1547,
                    1176,
                    1437,
                    1554,
                    1315,
                    852,
                    1068,
                    998,
                    1476,
                    2715,
                    495,
                    1102,
                    1921,
                    1835,
                    1342,
                    2373,
                    2075,
                    2285,
                    1349,
                    2515,
                    2223
                ],
                [
                    902,
                    1731,
                    1589,
                    1923,
                    1734,
                    2813,
                    1510,
                    2330,
                    0,
                    2578,
                    1528,
                    2456,
                    1965,
                    2790,
                    2401,
                    2377,
                    2565,
                    1635,
                    1433,
                    1648,
                    2154,
                    2899,
                    1482,
                    1573,
                    3116,
                    2682,
                    1967,
                    2182,
                    909,
                    2170,
                    2037,
                    1436,
                    458,
                    2286,
                    1600,
                    2729,
                    2431,
                    415,
                    2247,
                    3222,
                    2277
                ],
                [
                    2341,
                    1320,
                    1057,
                    2034,
                    2152,
                    305,
                    2246,
                    584,
                    2616,
                    0,
                    1351,
                    1523,
                    2400,
                    1780,
                    1893,
                    250,
                    1760,
                    1718,
                    1911,
                    1392,
                    2057,
                    629,
                    1686,
                    1803,
                    1905,
                    1223,
                    1113,
                    1588,
                    1725,
                    2881,
                    1004,
                    1351,
                    2170,
                    1816,
                    1470,
                    2538,
                    2240,
                    2534,
                    1155,
                    2278,
                    2389
                ],
                [
                    1282,
                    973,
                    444,
                    1369,
                    1357,
                    1609,
                    1277,
                    968,
                    1596,
                    1374,
                    0,
                    1963,
                    1581,
                    1682,
                    880,
                    1173,
                    747,
                    1018,
                    1100,
                    888,
                    1045,
                    1908,
                    937,
                    558,
                    1294,
                    1125,
                    1315,
                    726,
                    706,
                    1964,
                    833,
                    145,
                    1151,
                    1688,
                    842,
                    1873,
                    1575,
                    1514,
                    1595,
                    2366,
                    1724
                ],
                [
                    1770,
                    687,
                    1381,
                    1078,
                    1198,
                    1459,
                    1635,
                    1459,
                    2415,
                    1283,
                    1675,
                    0,
                    1674,
                    2530,
                    2217,
                    1159,
                    2084,
                    777,
                    1106,
                    824,
                    2381,
                    1381,
                    974,
                    2015,
                    2366,
                    1973,
                    438,
                    2062,
                    1524,
                    1816,
                    1328,
                    1675,
                    1969,
                    637,
                    799,
                    1474,
                    1176,
                    2333,
                    130,
                    801,
                    1324
                ],
                [
                    804,
                    1094,
                    1468,
                    722,
                    550,
                    2682,
                    353,
                    2209,
                    1989,
                    2308,
                    1569,
                    1594,
                    0,
                    3117,
                    2479,
                    2120,
                    2346,
                    830,
                    535,
                    1229,
                    2643,
                    2604,
                    770,
                    1614,
                    2729,
                    2560,
                    1458,
                    2324,
                    950,
                    405,
                    1916,
                    1477,
                    1395,
                    1323,
                    963,
                    964,
                    666,
                    1758,
                    1470,
                    1457,
                    512
                ],
                [
                    2967,
                    2315,
                    1683,
                    2744,
                    2823,
                    1665,
                    2871,
                    1372,
                    2990,
                    1751,
                    1657,
                    2757,
                    3026,
                    0,
                    1150,
                    1667,
                    1001,
                    2392,
                    2537,
                    2063,
                    987,
                    2278,
                    2312,
                    2203,
                    326,
                    780,
                    2108,
                    765,
                    2351,
                    3590,
                    1370,
                    1791,
                    2997,
                    2874,
                    2217,
                    3248,
                    2950,
                    2653,
                    2388,
                    3554,
                    3098
                ],
                [
                    2087,
                    1768,
                    1103,
                    2164,
                    2243,
                    1693,
                    2082,
                    1382,
                    2491,
                    1904,
                    893,
                    2493,
                    2446,
                    1621,
                    0,
                    1703,
                    254,
                    1812,
                    1957,
                    1610,
                    247,
                    2438,
                    1732,
                    1225,
                    893,
                    1089,
                    1844,
                    433,
                    1511,
                    3010,
                    1218,
                    928,
                    1955,
                    2611,
                    1637,
                    2668,
                    2370,
                    2154,
                    2125,
                    3291,
                    2518
                ],
                [
                    2121,
                    1119,
                    837,
                    1834,
                    1952,
                    385,
                    2026,
                    309,
                    2396,
                    250,
                    1131,
                    1378,
                    2180,
                    1670,
                    1673,
                    0,
                    1540,
                    1517,
                    1691,
                    1191,
                    1837,
                    844,
                    1466,
                    1583,
                    1577,
                    1114,
                    912,
                    1260,
                    1505,
                    2680,
                    784,
                    1131,
                    1950,
                    1671,
                    1269,
                    2338,
                    2040,
                    2314,
                    1010,
                    2176,
                    2188
                ],
                [
                    1833,
                    1514,
                    849,
                    1910,
                    1989,
                    1617,
                    1828,
                    1257,
                    2702,
                    1650,
                    639,
                    2239,
                    2192,
                    1176,
                    294,
                    1449,
                    0,
                    1559,
                    1703,
                    1356,
                    458,
                    2184,
                    1478,
                    1087,
                    995,
                    1045,
                    1591,
                    328,
                    1257,
                    2756,
                    964,
                    675,
                    1702,
                    2357,
                    1383,
                    2414,
                    2116,
                    2365,
                    1871,
                    3037,
                    2264
                ],
                [
                    1005,
                    404,
                    792,
                    421,
                    429,
                    1860,
                    870,
                    1603,
                    1694,
                    1667,
                    1035,
                    960,
                    827,
                    2441,
                    1803,
                    1480,
                    1670,
                    0,
                    338,
                    470,
                    1967,
                    1782,
                    206,
                    1294,
                    2053,
                    1884,
                    636,
                    1648,
                    803,
                    1267,
                    1240,
                    1086,
                    1248,
                    851,
                    234,
                    925,
                    627,
                    1612,
                    656,
                    1418,
                    775
                ],
                [
                    667,
                    798,
                    1047,
                    597,
                    408,
                    2253,
                    532,
                    1787,
                    1418,
                    1886,
                    1148,
                    1130,
                    489,
                    2696,
                    2057,
                    1699,
                    1924,
                    409,
                    0,
                    807,
                    2221,
                    2175,
                    348,
                    1193,
                    2307,
                    2139,
                    1030,
                    1902,
                    528,
                    1016,
                    1494,
                    1055,
                    973,
                    961,
                    541,
                    1101,
                    803,
                    1337,
                    1042,
                    1594,
                    952
                ],
                [
                    1017,
                    219,
                    561,
                    718,
                    872,
                    1628,
                    921,
                    1085,
                    1591,
                    1227,
                    803,
                    1115,
                    1076,
                    2156,
                    1571,
                    1039,
                    1438,
                    367,
                    587,
                    0,
                    1736,
                    1550,
                    362,
                    1191,
                    1822,
                    1599,
                    466,
                    1417,
                    700,
                    1564,
                    955,
                    804,
                    1145,
                    967,
                    154,
                    1222,
                    924,
                    1509,
                    746,
                    1912,
                    1073
                ],
                [
                    2245,
                    1925,
                    1261,
                    2321,
                    2400,
                    1850,
                    2239,
                    1540,
                    2244,
                    2061,
                    1050,
                    2651,
                    2603,
                    1407,
                    247,
                    1860,
                    411,
                    1970,
                    2115,
                    1767,
                    0,
                    2595,
                    1890,
                    1084,
                    680,
                    1247,
                    2002,
                    590,
                    1668,
                    3849,
                    1375,
                    1086,
                    2251,
                    2768,
                    1795,
                    2825,
                    2527,
                    1907,
                    2282,
                    3448,
                    2676
                ],
                [
                    2525,
                    1437,
                    1576,
                    2152,
                    2308,
                    644,
                    2430,
                    1296,
                    3100,
                    644,
                    1869,
                    1608,
                    2584,
                    2316,
                    2411,
                    859,
                    2278,
                    1835,
                    2095,
                    1509,
                    2576,
                    0,
                    1870,
                    2321,
                    2243,
                    1599,
                    1230,
                    1926,
                    2209,
                    2971,
                    1522,
                    1870,
                    2654,
                    1901,
                    1587,
                    2629,
                    2331,
                    3018,
                    1239,
                    2176,
                    2480
                ],
                [
                    950,
                    352,
                    671,
                    613,
                    556,
                    1910,
                    815,
                    1412,
                    1530,
                    1508,
                    913,
                    1152,
                    772,
                    2320,
                    1682,
                    1320,
                    1549,
                    198,
                    283,
                    429,
                    1846,
                    1831,
                    0,
                    1131,
                    1932,
                    1763,
                    747,
                    1527,
                    640,
                    1164,
                    1118,
                    923,
                    1085,
                    1043,
                    221,
                    1116,
                    819,
                    1449,
                    848,
                    1610,
                    967
                ],
                [
                    1314,
                    1319,
                    914,
                    1715,
                    1474,
                    2138,
                    1309,
                    1655,
                    1940,
                    1903,
                    555,
                    2072,
                    1613,
                    2836,
                    1236,
                    1702,
                    1193,
                    1276,
                    1231,
                    1234,
                    1095,
                    2224,
                    1123,
                    0,
                    1763,
                    1670,
                    1423,
                    1171,
                    737,
                    2082,
                    1362,
                    426,
                    1182,
                    2034,
                    1188,
                    2219,
                    1921,
                    1603,
                    1703,
                    2712,
                    2069
                ],
                [
                    2603,
                    2273,
                    1431,
                    2491,
                    2570,
                    1706,
                    2619,
                    1396,
                    3067,
                    2001,
                    1384,
                    2715,
                    2773,
                    350,
                    944,
                    1691,
                    745,
                    2140,
                    2284,
                    1937,
                    771,
                    2313,
                    2059,
                    1843,
                    0,
                    866,
                    2066,
                    708,
                    2027,
                    3337,
                    1328,
                    1517,
                    3073,
                    2832,
                    1965,
                    2995,
                    2697,
                    2730,
                    2346,
                    3512,
                    2846
                ],
                [
                    2214,
                    1563,
                    931,
                    1992,
                    2070,
                    885,
                    2119,
                    574,
                    2490,
                    1180,
                    905,
                    2004,
                    2274,
                    911,
                    868,
                    870,
                    720,
                    1640,
                    1785,
                    1311,
                    1033,
                    1491,
                    1560,
                    1451,
                    800,
                    0,
                    1356,
                    483,
                    1599,
                    2838,
                    618,
                    1039,
                    2044,
                    2122,
                    1465,
                    2495,
                    2198,
                    2939,
                    1636,
                    2802,
                    2346
                ],
                [
                    1456,
                    366,
                    997,
                    973,
                    1091,
                    1331,
                    1361,
                    1075,
                    2031,
                    1139,
                    1291,
                    649,
                    1516,
                    2146,
                    1833,
                    951,
                    1700,
                    656,
                    1027,
                    440,
                    1998,
                    1253,
                    802,
                    1631,
                    1983,
                    1589,
                    0,
                    1679,
                    1140,
                    1819,
                    944,
                    1291,
                    1585,
                    942,
                    501,
                    1477,
                    1179,
                    1949,
                    280,
                    1446,
                    1328
                ],
                [
                    1919,
                    1600,
                    935,
                    1996,
                    2074,
                    1307,
                    1914,
                    997,
                    2832,
                    1602,
                    724,
                    2325,
                    2278,
                    800,
                    424,
                    1292,
                    275,
                    1644,
                    1789,
                    1442,
                    588,
                    1914,
                    1564,
                    1172,
                    619,
                    704,
                    1676,
                    0,
                    1342,
                    2842,
                    930,
                    760,
                    1787,
                    2443,
                    1469,
                    2499,
                    2201,
                    2495,
                    1957,
                    3122,
                    2350
                ],
                [
                    693,
                    822,
                    681,
                    1101,
                    911,
                    1904,
                    688,
                    1421,
                    1007,
                    1669,
                    620,
                    1634,
                    992,
                    2330,
                    1428,
                    1468,
                    1295,
                    726,
                    610,
                    740,
                    1592,
                    1990,
                    573,
                    665,
                    1942,
                    1773,
                    1058,
                    1273,
                    0,
                    1519,
                    1128,
                    527,
                    561,
                    1464,
                    691,
                    1604,
                    1306,
                    925,
                    1338,
                    2098,
                    1455
                ],
                [
                    1307,
                    1019,
                    1430,
                    317,
                    408,
                    2474,
                    1066,
                    2218,
                    2249,
                    2281,
                    1672,
                    1188,
                    457,
                    3079,
                    2440,
                    2094,
                    2307,
                    714,
                    940,
                    1120,
                    2605,
                    2396,
                    911,
                    2019,
                    2691,
                    2522,
                    1250,
                    2286,
                    1354,
                    0,
                    1877,
                    1673,
                    1799,
                    918,
                    884,
                    559,
                    261,
                    2647,
                    1188,
                    1052,
                    107
                ],
                [
                    1596,
                    945,
                    313,
                    1373,
                    1452,
                    1032,
                    1501,
                    553,
                    1871,
                    797,
                    606,
                    1386,
                    1655,
                    1461,
                    1149,
                    596,
                    1016,
                    1022,
                    1167,
                    693,
                    1313,
                    1331,
                    941,
                    1059,
                    1298,
                    904,
                    737,
                    994,
                    981,
                    2220,
                    0,
                    607,
                    1426,
                    1504,
                    847,
                    1877,
                    1579,
                    1790,
                    1018,
                    2184,
                    1728
                ],
                [
                    1169,
                    884,
                    480,
                    1280,
                    1280,
                    1593,
                    1165,
                    1110,
                    1484,
                    1358,
                    145,
                    1637,
                    1469,
                    1816,
                    916,
                    1157,
                    783,
                    928,
                    1024,
                    799,
                    1080,
                    1789,
                    848,
                    423,
                    1428,
                    1260,
                    988,
                    761,
                    593,
                    1888,
                    817,
                    0,
                    1038,
                    1599,
                    753,
                    1784,
                    1486,
                    1402,
                    1268,
                    2277,
                    1634
                ],
                [
                    531,
                    1324,
                    1183,
                    1517,
                    1327,
                    2407,
                    1104,
                    1924,
                    485,
                    2171,
                    1122,
                    2050,
                    1408,
                    2912,
                    1930,
                    1970,
                    1797,
                    1229,
                    1026,
                    1242,
                    2275,
                    2493,
                    1076,
                    1167,
                    2444,
                    2275,
                    1560,
                    1776,
                    502,
                    1935,
                    1630,
                    1030,
                    0,
                    1880,
                    1194,
                    2020,
                    1722,
                    403,
                    1841,
                    2514,
                    1871
                ],
                [
                    1532,
                    799,
                    1469,
                    698,
                    960,
                    1960,
                    1397,
                    1960,
                    2283,
                    1784,
                    1711,
                    533,
                    1283,
                    3031,
                    2718,
                    1660,
                    2585,
                    753,
                    979,
                    1041,
                    2882,
                    1882,
                    950,
                    2058,
                    2868,
                    2474,
                    939,
                    2563,
                    1393,
                    1425,
                    1829,
                    1712,
                    1838,
                    0,
                    911,
                    1082,
                    784,
                    2202,
                    644,
                    623,
                    933
                ],
                [
                    1099,
                    193,
                    645,
                    564,
                    682,
                    1702,
                    1003,
                    1233,
                    1673,
                    1374,
                    887,
                    1017,
                    961,
                    2294,
                    1655,
                    1186,
                    1522,
                    212,
                    472,
                    295,
                    1820,
                    1624,
                    246,
                    1273,
                    1906,
                    1737,
                    517,
                    1501,
                    782,
                    1410,
                    1092,
                    888,
                    1227,
                    909,
                    0,
                    1068,
                    770,
                    1591,
                    713,
                    1561,
                    918
                ],
                [
                    1564,
                    1309,
                    1720,
                    607,
                    926,
                    2764,
                    1630,
                    2508,
                    2864,
                    2572,
                    1963,
                    1478,
                    1020,
                    3369,
                    2731,
                    2384,
                    2598,
                    1004,
                    1230,
                    1411,
                    2895,
                    2686,
                    1201,
                    2309,
                    2981,
                    2812,
                    1540,
                    2576,
                    1644,
                    1162,
                    2168,
                    1963,
                    2089,
                    1208,
                    1175,
                    0,
                    426,
                    3262,
                    1478,
                    1342,
                    532
                ],
                [
                    1185,
                    930,
                    1341,
                    228,
                    547,
                    2385,
                    1250,
                    2128,
                    2433,
                    2192,
                    1583,
                    1099,
                    640,
                    2990,
                    2351,
                    2005,
                    2218,
                    625,
                    851,
                    1031,
                    2515,
                    2307,
                    822,
                    1930,
                    2602,
                    2433,
                    1161,
                    2197,
                    1265,
                    782,
                    1788,
                    1583,
                    1710,
                    829,
                    795,
                    345,
                    0,
                    2073,
                    1098,
                    963,
                    290
                ],
                [
                    1370,
                    1586,
                    1445,
                    1778,
                    1589,
                    2668,
                    1365,
                    2185,
                    448,
                    2433,
                    1383,
                    2311,
                    1670,
                    2604,
                    2215,
                    2232,
                    2379,
                    1490,
                    1288,
                    1503,
                    1968,
                    2754,
                    1337,
                    1429,
                    2930,
                    2537,
                    1822,
                    2558,
                    764,
                    2545,
                    1892,
                    1291,
                    382,
                    2141,
                    1455,
                    2282,
                    1984,
                    0,
                    2102,
                    2775,
                    2133
                ],
                [
                    1711,
                    571,
                    1252,
                    962,
                    1082,
                    1329,
                    1519,
                    1329,
                    2285,
                    1153,
                    1545,
                    382,
                    1476,
                    2400,
                    2088,
                    1029,
                    1954,
                    661,
                    990,
                    694,
                    2252,
                    1251,
                    858,
                    1885,
                    2237,
                    1843,
                    308,
                    1933,
                    1395,
                    1745,
                    1199,
                    1546,
                    1840,
                    675,
                    683,
                    1403,
                    1105,
                    2203,
                    0,
                    844,
                    1253
                ],
                [
                    2010,
                    1698,
                    2330,
                    1053,
                    1372,
                    2175,
                    2076,
                    2407,
                    3258,
                    2175,
                    2623,
                    690,
                    1466,
                    3478,
                    3166,
                    2107,
                    3032,
                    1450,
                    1676,
                    1772,
                    3330,
                    2097,
                    1647,
                    2755,
                    3315,
                    2921,
                    1386,
                    3011,
                    2090,
                    1608,
                    2277,
                    2624,
                    2535,
                    653,
                    1621,
                    1265,
                    967,
                    2899,
                    1277,
                    0,
                    1116
                ],
                [
                    1359,
                    1076,
                    1487,
                    374,
                    465,
                    2531,
                    1118,
                    2275,
                    2300,
                    2338,
                    1729,
                    1245,
                    508,
                    3136,
                    2498,
                    2151,
                    2365,
                    771,
                    997,
                    1178,
                    2662,
                    2453,
                    968,
                    2076,
                    2748,
                    2579,
                    1307,
                    2343,
                    1411,
                    650,
                    1934,
                    1730,
                    1856,
                    975,
                    942,
                    389,
                    128,
                    2698,
                    1245,
                    1109,
                    0
                ]
            ]
        }
    }
}

**Comment by jcoupey** [comment] 2021-06-18 10:27
This is likely a json parsing error. What command did you run exactly?

**Comment by prince4249** [comment] 2021-06-18 10:44
Hi Julien ,
Thanks for reverting back. I ran **./bin/vroom -i data.json -o output.json** 
data file is correctly json formatted

**Comment by jcoupey** [comment] 2021-06-18 10:57
That's weird, I'm getting solutions on your example with both `v1.10.0` and current `master`. What version of `vroom` did you build?

Is there maybe something special going on around file encoding or escaping on your side? The `offset: 0` part seems to indicate that the json parsing fails right away.

**Comment by prince4249** [comment] 2021-06-18 11:02
I am using v1.10.0

**Comment by jcoupey** [comment] 2021-06-18 11:09
What if you `cat data.json | vroom`?

**Comment by prince4249** [comment] 2021-06-21 03:39
I didn't get your point

**Comment by jcoupey** [comment] 2021-06-21 08:08
I mean running this as a command: `cat data.json | vroom` (maybe adjust the `vroom` part to the exact path). The difference is that then `vroom` would read from standard input instead of using `-i`.

Another easy test: are you able to run on the provided standalone example at `docs/example_2.json`?

**Comment by jcoupey** [comment] 2021-07-01 15:25
@prince4249 did you sort this problem out? If yes, please close the ticket.

**Comment by prince4249** [comment] 2021-07-01 15:48
> I mean running this as a command: `cat data.json | vroom` (maybe adjust the `vroom` part to the exact path). The difference is that then `vroom` would read from standard input instead of using `-i`.
> 
> Another easy test: are you able to run on the provided standalone example at `docs/example_2.json`?

Not really . doc/example_2.json is working by the way.

**Comment by jcoupey** [comment] 2021-07-01 15:51
>doc/example_2.json is working by the way

OK, and what about the other question (using `cat` and piping to `vroom`)?

**Comment by prince4249** [comment] 2021-07-01 15:58
cat data.json | vroom , I run this command in this same directory where I was running the above mentioned command . cat data.json | vroom results in error vroom : command not found

**Comment by jcoupey** [comment] 2021-07-02 22:41
That's the "adjust the vroom part to the exact path" part. Based on your previous command report, you should run:

```
cat data.json | ./bin/vroom
```

Then the solution should appear on standard output (or you can add `-o output.json` to try writing to a file).

**Comment by prince4249** [comment] 2021-07-04 15:49
Uggh , I don't know but still getting the same error. 
[Error] Invalid value. (offset: 0)
{"code":2,"error":"Invalid value. (offset: 0)"}

**Comment by jcoupey** [comment] 2021-07-05 07:22
Considering that:
- the error you're seeing comes from `rapidjson` (the library we use to parse input data)
- the `docs/example_2.json` file works for you
- we can't reproduce the problem by simply pasting your example to a file
 
I think you have a problem in the way your json input file is formatted. You may get more feedback on potential problems by trying to parse your file with other tools, like `jsonlint` or `jq`. If there's a formatting problem, they'll report it to you.

This is now outside the scope of this repo so I'm closing this ticket.

**Closed by jcoupey** 2021-07-05 07:22 UTC
Labels: question
