### ISSUE TITLE
Multi-trip routing problem 

### ISSUE THREAD

**Issue by tediyuwono** [VROOM-Project/vroom#188] opened 2018-12-12 11:15 UTC
Support I have 9 jobs and 3 vehicles and time windows of each job is 3 hour.
Vroom result will be 3 routes each with 3 jobs ( route A  and B are each 1 hour, and route C is 3 hour).

if I only have 2 vehicles, vroom will result Route A and B, the the jobs were assigned in route C is remain unassigned.
But with that solution those unassigned jobs will be remain unassigned after the vehicles are coming back, and we call vroom again, because of the time window.
Actually we can deliver all jobs within time windows if we Route A and Route C are processed in the first batch. And Route B can be performed in the second batch.

Is there any plan to support multi batch route plan in case the vehicles are not sufficient to cover at one batch?

following are sample scenario:
{
  "vehicles": [
    {
      "id": 1,
      "start": [
        106.773814,
		-6.161013
      ],
      "startDescription": "Depo",
      "end": [
        106.773814,
		-6.161013
      ],
      "endDescription": "Depo",
      "capacity": [
        10000
      ],
      "skills": [
        0
      ]
    },
	{
      "id": 2,
      "start": [
        106.773814,
		-6.161013
      ],
      "startDescription": "Depo",
      "end": [
        106.773814,
		-6.161013
      ],
      "endDescription": "Depo",
      "capacity": [
        10000
      ],
      "skills": [
        0
      ]
    },
	{
      "id": 3,
      "start": [
        106.773814,
		-6.161013
      ],
      "startDescription": "Depo",
      "end": [
        106.773814,
		-6.161013
      ],
      "endDescription": "Depo",
      "capacity": [
        10000
      ],
      "skills": [
        0
      ]
    }
  ],
  "jobs": [	
    {
      "id": 1,
      "description": "CustomerID: 1",
      "service": 720,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.785392,
        -6.139403
      ],
      "skills": [
        0
      ],
      "amount": [
        3000
      ]
    },
    {
      "id": 2,
      "description": "CustomerID: 2",
      "service": 720,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.785392,
        -6.159818
      ],
      "skills": [
        0
      ],
      "amount": [
        3000
      ]
    },
	{
      "id": 3,
      "description": "CustomerID: 3",
      "service": 720,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.783918,
        -6.171351
      ],
      "skills": [
        0
      ],
      "amount": [
        3000
      ]
    },
	{
      "id": 4,
      "description": "CustomerID: 4",
      "service": 720,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.761798,
        -6.170788
      ],
      "skills": [
        0
      ],
      "amount": [
        4000
      ]
    },
	{
      "id": 5,
      "description": "CustomerID: 5",
      "service": 720,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.784739,
        -6.148825
      ],
      "skills": [
        0
      ],
      "amount": [
        3000
      ]
    },
	{
      "id": 6,
      "description": "CustomerID: 6",
      "service": 720,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.798665,
        -6.15301
      ],
      "skills": [
        0
      ],
      "amount": [
        3000
      ]
    },
	{
      "id": 7,
      "description": "CustomerID: 7",
      "service": 3500,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.523054,
        -6.216774
      ],
      "skills": [
        0
      ],
      "amount": [
        3000
      ]
    },
	{
      "id": 8,
      "description": "CustomerID: 8",
      "service": 3500,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.531892,
        -6.265107
      ],
      "skills": [
        0
      ],
      "amount": [
        3000
      ]
    },
	{
      "id": 9,
      "description": "CustomerID: 9",
      "service": 720,
      "time_windows": [
        [
          36000,
          46800
        ]
      ],
      "location": [
        106.584926,
        -6.232696
      ],
      "skills": [
        0
      ],
      "amount": [
        3000
      ]
    }
  ],
  "options": {
    "g": true
  }
}

Route C is the job 7,8,9

Thanks and Regards,

**Comment by jcoupey** [comment] 2018-12-12 16:10
If I'm getting it right, the problem is that a single vehicle can't handle 6 jobs in a row due to the capacity constraints. So you'd like to have one vehicle doing 3 jobs in a first trip, then get back to the depot, then handle the remaining 3 jobs?

**Comment by tediyuwono** [comment] 2018-12-13 01:07
> If I'm getting it right, the problem is that a single vehicle can't handle 6 jobs in a row due to the capacity constraints. So you'd like to have one vehicle doing 3 jobs in a first trip, then get back to the depot, then handle the remaining 3 jobs?

Yes, but AFAIK because vroom doesn't consider possible next trip (in case there are unassigned jobs), it could happen as in the sample scenario, that the remaining unassigned jobs are remain unassigned when we call vrom again with only remaining jobs (and the vehicle time window start after return time from first trip) because of the time window.

**Comment by jcoupey** [comment] 2018-12-13 09:35
This turns up as "multi-trip" VRPTW in a few research papers and you're right we don't handle that right now. There is no short-time plan to implement this but I just flagged this ticket to keep track of the idea.

In the meantime, there are some ways to circumvent the problem that may be good enough for your use-case. In order to obtain two trips for the same vehicle, you can define two different time-windows. For example I'm getting a solution with only two vehicles if I naively split the `[36000, 46800]` planning horizon in two for vehicle 2. If you compare [the original solution](http://map.vroom-project.org/?q=1faa7a4edaff) with the [two-vehicle solution](http://map.vroom-project.org/?q=b6bd2f86bab8), you'll notice that travel times and routes are identical, the two shortest routes are simply done one after another with the same vehicle and arrival times are shifted accordingly.

Vehicle definition for the json input used:
```json
"vehicles": [
  {
    "id": 1,
    "start": [
      106.773814,
      -6.161013
    ],
    "startDescription": "Depo",
    "end": [
      106.773814,
      -6.161013
    ],
    "endDescription": "Depo",
    "capacity": [
      10000
    ],
    "skills": [
      0
    ]
  },
  {
    "id": 2,
    "start": [
      106.773814,
      -6.161013
    ],
    "startDescription": "Depo",
    "end": [
      106.773814,
      -6.161013
    ],
    "endDescription": "Depo",
    "capacity": [
      10000
    ],
    "skills": [
      0
    ],
    "time_window": [36000, 41400]
  },
  {
    "id": 2,
    "start": [
      106.773814,
      -6.161013
    ],
    "startDescription": "Depo",
    "end": [
      106.773814,
      -6.161013
    ],
    "endDescription": "Depo",
    "capacity": [
      10000
    ],
    "skills": [
      0
    ],
    "time_window": [41400, 46800]
  }
],
```

**Comment by jcoupey** [comment] 2020-03-23 08:51
Update: the expected behaviour of getting back to the depot to fill a vehicle, then go back for deliveries can now be achieved using `shipment` objects.

Instead of defining deliveries as a `job` object, define it as a `shipment` whose `pickup` place is the depot. Then we'll be able to output routes that start with a number of pickups (depending on vehicle capacity), then do the associated deliveries, then go back for another row of pickups and so forth, all in the same route.

Using this flexible modelling has one major drawback: the number of "locations" involved in the optimization problem will basically double (even if half of them are similar). This will have an impact on computing times, but then you can't have your cake and eat it too.

**Comment by jcoupey** [comment] 2020-03-23 08:51
Closing as this is now possible. Please open a new dedicated ticket for any trouble using the above approach.

**Closed by jcoupey** 2020-03-23 08:51 UTC
Labels: feature request
