### ISSUE TITLE
Invalid time_window for vehicle

### ISSUE THREAD

**Issue by viorelpv** [VROOM-Project/vroom#162] opened 2018-09-19 14:52 UTC
Dear Vroom team,

About few  days I've tested your application in the educational purpose and in my opinion is a great piece of work.
reason that I'm writing this email is that I really need you help with to guide me how to format time window variable.
I read the provided documentation, but for one like me without programming knowledge is very hard to understand.

I've created a json file that looks like this (end of the message), but i keep receiving error code 1  time window is invalid.
This file was created in the purpose of presenting the impact of costs using a route optimization software  to a couple of kids from the general school and how technology can improve our work productivity .
Would you be kind and take a look at this file and tell me what I'm doing wrong?
Thank you in advance and keep up the good work!

curl --header "Content-Type:application/json" --data '
{
  "vehicles": [
    {
      "id": 0,
      "start": [21.175346,45.670246],
      "end": [21.175346,45.670246],
      "capacity": [2700],
      "skills": [60,65],
      "time_window": { "start":0,"end":40872}
    }
  ],
  "jobs": [
    {
      "id": 0,
      "location": [21.235783,45.728685],
      "service": 300,
      "amount": [705],
      "skills": [65],
      "time_windows": [{"start":0,"end":37872}]
    },
    {
      "id": 1,
      "location": [21.239642,45.766877],
      "service": 300,
      "amount": [140],
      "skills": [60],
      "time_windows": [{"start":0,"end":37872}]
    },
{"id": 2,
      "location": [21.199733,45.723465],
      "service": 300,
      "amount": [140],
      "skills": [60],
      "time_windows": [{"start":26000,"end":37872}]
}
  ],"options":{"g":true}}' http://solver.vroom-project.org

**Comment by jcoupey** [comment] 2018-09-19 19:28
@viorelpv thanks for your feedback.

You need to use a plain array to describe time windows: `{ "start":0,"end":40872}` should actually be `[0,40872]`.

Please note that the demo server at http://solver.vroom-project.org will not throw an error with your json file, simply because it runs an older version that is behind the current `master` (the `time_window` and `time_windows` keys are completely ignored).

Also you need to be aware that if you're using the current `master` branch with time windows, you might get poor solutions as the feature is still very much a work in progress. I would not consider it very reliable before #159 gets merged.

**Comment by viorelpv** [comment] 2018-10-01 08:19
@jcoupey  Thank you for your prompt reply. 
Indeed, the demo server does not throw time window error. 
Anyway I didn't succeed to test and present this solution with time windows due the same error message - "invalid time window" ( on a local server ), but everything else worked perfect! 
Thank again for your time and making this possible !

Just for my info, If you are kind enough to let me know what I did wrong -  I used as you specified an plain array for vehicle time window and a array of objects for job time windows as : 
time_window :  [0,40872]
time_windows : [{"start": 0, "end":10430}]
I suppose that my limited knowledge about JSON is the reason for this error.

All the best for this nice project!

**Comment by jcoupey** [comment] 2018-10-01 15:29
A `time_window` object is a pair of timestamps in the form `[start, end]`, so you need to use the same syntax for vehicle and job time windows: replace `"time_windows": [{"start": 0, "end":10430}]` by `"time_windows": [[0,10430]]`. Having an array of time windows for jobs allows to specify several availability slots.

I'll make sure to update the [docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#examples) with a more complete example to make it easier to get started with the API syntax.

**Comment by shiromdk** [comment] 2018-10-04 02:50
What kind of timestamps are the start and end times? Are they just arbitrary numbers or something?

**Comment by jcoupey** [comment] 2018-10-04 14:42
@shiromdk start and end times are 32 bits unsigned integers (`uint32_t`). That limitation aside, how to use them depend on the way you want to model your problems. You can use:

- relative values, e.g. `[0, 14400]` for a 4 hours time window starting at the beginning of your planning horizon, whatever that means for you. In that case all times reported in output with the `arrival` key are relative to the start of the planning horizon.
- absolute values, "real" timestamps. In that case all times reported in output with the `arrival` key can be interpreted as absolute timestamps.

Note that omitting a time window for a vehicle or a job is just like providing an extra-large one starting at 0 and ending at the max value.

**Comment by jcoupey** [comment] 2018-10-17 07:12
Closing here, feel free to re-open for a follow-up question.

**Closed by jcoupey** 2018-10-17 07:12 UTC
Labels: question

**Comment by gitbitlit** [comment] 2019-02-22 09:11
As a newbie to VRP, my questions may be dumb, i sincerely appreciate any help.

1. Does `time_window` for trucks, `time_windows` for jobs works with custom travel time matrix ?
2. If units of custom travel time matrix is in minutes, does that mean time window numbers too should be in minutes ?
3. Each time window with in `time_windows` of a job denotes accepted delivery times of that job at its location ?
4. Is it required for provide some where in request json file, the reference abs date and units of time used for time window numbers ?

We are providing time window numbers as minutes from 1-Jan-2019.

Using http://map.vroom-project.org/, uploading a sample problem file **without** time windows and with vehicle capacity optimization gives good clustered results BUT we failed to get any reasonable understating of results when we are using time windows.

**Comment by jcoupey** [comment] 2019-02-22 17:29
1. Yes, no problem with using timing constraints along with a custom matrix, provided the matrix values are consistent (units and reference).

2. Yes. The API documentation states that "all timings are in seconds". More precisely it's required to use seconds with OSRM, as the retrieved travel times in the matrix are in seconds. If you input your own matrix, you can use any unit provided it's consistent across all timing-related fields (matrix values, time windows, job service duration). The unit in output for time-related fields (`arrival`, `duration`, `waiting_time`) will match.

3. Yes, in order for a job to be included in the solution, it's service time has to **start** in one of the provided time windows. Note that the `arrival` time in the response might be out of the time window for an early arrival, resulting in a non-zero waiting time.

4. No, you have to decided for yourself how you want to model your problem. The typical way to do that is to describe times as a number of seconds (or whatever unit) since the beginning of the planning horizon. Using any kind of timestamp will be OK, as long as all values are consistent, you'll just have to translate the output to real dates based on your reference choice.

**Comment by gitbitlit** [comment] 2019-02-26 10:30
As I failed to pinpoint my ambiguity, so i expressed it in 4 points. Really appreciate your point by point reply. Thank you.

Before getting back to this thread, I tried multiple combinations of capacities and time windows on demo server at map.vroom-project.org


Still, I am yet to understand.


At this point I believe, it is beyond my capacities to explain this in text/script, so I am resorting to using a sample request file.

This sample request file contains :

- 3 Trucks each with capacity 5000
- 3 Jobs each with amount 5000
- 1 warehouse
- No `time_window` on trucks
- Job `time_windows` are well within the travel time
- Custom travel matrix in minutes

[vrp_tw_3_trucks_3_jobs.txt](https://github.com/VROOM-Project/vroom/files/2904952/vrp_tw_3_trucks_3_jobs.txt)

For this problem request file http://map.vroom-project.org/ says no possible solutions.

If i bump each job `time_windows` end time by *100, i will get the expected result. i.e 3 trucks dispatched to 3 job locations

What I need to learn  and/or how i need to understand the above results ?

**Comment by gitbitlit** [comment] 2019-02-26 13:08
To my surprise, the same sample request submitted to vroom binary v1.3.0 running on AWS Linux giving us the expected results.  i.e 3 trucks dispatched to 3 job locations

Solution response file from vroom binary v1.3.0 attached 
[vrp_tw_3_trucks_3_jobs_v1.3.0.txt](https://github.com/VROOM-Project/vroom/files/2905538/vrp_tw_3_trucks_3_jobs_v1.3.0.txt)

**Comment by jcoupey** [comment] 2019-02-26 20:36
@gitbitlit the purpose of the demo frontend at http://map.vroom-project.org/ is to show optimization on top of OSRM real-life routing. Any problem you input there will go through the OSRM pipeline, so in your case the `matrix` and `location_index` keys are completely ignored. The cost matrix is recomputed with OSRM **in seconds**, which explain that the problem is not feasible with your initial time windows in minutes, but doable if you raise the deadlines.

If you have a fully formatted problem with a custom matrix, you want to hit the demo server directly. For example I'm getting the exact solution you posted running:
```
curl --header "Content-Type:application/json" --data @vrp_tw_3_trucks_3_jobs.txt http://solver.vroom-project.org 
```

**Comment by gitbitlit** [comment] 2019-02-27 09:29
Thank you @jcoupey
